---
title: "Data_modelling"
output: html_document
date: '2023-03-17'
---

```{r setup, include=FALSE}
# Import packages
library(tidyverse)
library(lubridate)
library(timetk)
library(RcppRoll)
library(dLagM)
library(dlnm)
library(zoo)
theme_set(theme_gray())
# Mapping imports
library(sf)
library(leaflet)
library(tmap)
library(gridExtra)
tmap_options(check.and.fix = TRUE)

# Read data
hydro_summer_20203 <- readRDS(file = "./data/hydro_summer_20203.RDS")
hydro_summer_11502 <- readRDS(file = "./data/hydro_summer_11502.RDS")
hydro_summer_10304 <- readRDS(file = "./data/hydro_summer_10304.RDS")
hydro_winter_20203 <- readRDS(file = "./data/hydro_winter_20203.RDS")
hydro_winter_11502 <- readRDS(file = "./data/hydro_winter_11502.RDS")
hydro_winter_10304 <- readRDS(file = "./data/hydro_winter_10304.RDS")
hydro_total <- readRDS(file = "./data/hydro_total.RDS")
pegel_prop <- readRDS(file = "./data/pegel_prop.RDS")
# Add rescaled soilwater
hydro_summer_20203$soilwater100 <- hydro_summer_20203$soilwater * 100
hydro_summer_11502$soilwater100 <- hydro_summer_11502$soilwater * 100
hydro_summer_10304$soilwater100 <- hydro_summer_10304$soilwater * 100
hydro_winter_20203$soilwater100 <- hydro_winter_20203$soilwater * 100
hydro_winter_11502$soilwater100 <- hydro_winter_11502$soilwater * 100
hydro_winter_10304$soilwater100 <- hydro_winter_10304$soilwater * 100

# separate datasets for each waterlevel, season and member
# winter
for (i in pegel_ids) {
  for (j in levels(hydro_total$member)) {
    assign(paste0("hydro_winter_", i, "_", j), hydro_winter %>% filter(name_waterlevel %in% i) %>% filter(member %in% j))
  }
}

# summer
for (i in pegel_ids) {
  for (j in levels(hydro_total$member)) {
    assign(paste0("hydro_summer_", i, "_", j), hydro_summer %>% filter(name_waterlevel %in% i) %>% filter(member %in% j))
  }
}
```


###### Basic linear models (might not be appropriate)
### ZV: Drainage

## Temp
``` {r}
# Summer
summary(lm(hydro_summer_10304$airtmp ~ hydro_summer_10304$drainage))
summer_temp_10304 <- ggplot(hydro_summer_10304, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$airtmp ~ hydro_summer_11502$drainage))
summer_temp_11502 <- ggplot(hydro_summer_11502, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$airtmp ~ hydro_summer_20203$drainage))
summer_temp_20203 <- ggplot(hydro_summer_20203, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_temp_10304, summer_temp_11502, summer_temp_20203, ncol = 2)


## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = airtmp, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

# Winter
summary(lm(hydro_winter_10304$airtmp ~ hydro_winter_10304$drainage))
winter_temp_10304 <- ggplot(hydro_winter_10304, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$airtmp ~ hydro_winter_11502$drainage))
winter_temp_11502 <- ggplot(hydro_winter_11502, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$airtmp ~ hydro_winter_20203$drainage))
winter_temp_20203 <- ggplot(hydro_winter_20203, aes(airtmp, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_temp_10304, winter_temp_11502, winter_temp_20203, ncol = 2)
grid.arrange(winter_temp_10304, winter_temp_11502, winter_temp_20203, 
             summer_temp_10304, summer_temp_11502, summer_temp_20203,ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = airtmp, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

## precip
```{r}
summary(lm(hydro_summer_10304$precip ~ hydro_summer_10304$drainage))
summer_precip_10304 <- ggplot(hydro_summer_10304, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$precip ~ hydro_summer_11502$drainage))
summer_precip_11502 <- ggplot(hydro_summer_11502, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$precip ~ hydro_summer_20203$drainage))
summer_precip_20203 <- ggplot(hydro_summer_20203, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_precip_10304, summer_precip_11502, summer_precip_20203, ncol = 2)
## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = precip, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
# Winter
summary(lm(hydro_winter_10304$precip ~ hydro_winter_10304$drainage))
winter_precip_10304 <- ggplot(hydro_winter_10304, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$precip ~ hydro_winter_11502$drainage))
winter_precip_11502 <- ggplot(hydro_winter_11502, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$precip ~ hydro_winter_20203$drainage))
winter_precip_20203 <- ggplot(hydro_winter_20203, aes(precip, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_precip_10304, winter_precip_11502, winter_precip_20203, ncol = 2)
grid.arrange(winter_precip_10304, winter_precip_11502, winter_precip_20203, 
             summer_precip_10304, summer_precip_11502, summer_precip_20203, ncol = 3)
## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = precip, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

## radiation
```{r}
summary(lm(hydro_summer_10304$glorad ~ hydro_summer_10304$drainage))
summer_glorad_10304 <- ggplot(hydro_summer_10304, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$glorad ~ hydro_summer_11502$drainage))
summer_glorad_11502 <- ggplot(hydro_summer_11502, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$glorad ~ hydro_summer_20203$drainage))
summer_glorad_20203 <- ggplot(hydro_summer_20203, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_glorad_10304, summer_glorad_11502, summer_glorad_20203, ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = glorad, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
# Winter
summary(lm(hydro_winter_10304$glorad ~ hydro_winter_10304$drainage))
winter_glorad_10304 <- ggplot(hydro_winter_10304, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$glorad ~ hydro_winter_11502$drainage))
winter_glorad_11502 <- ggplot(hydro_winter_11502, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$glorad ~ hydro_winter_20203$drainage))
winter_glorad_20203 <- ggplot(hydro_winter_20203, aes(glorad, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_glorad_10304, winter_glorad_11502, winter_glorad_20203, ncol = 2)
grid.arrange(winter_glorad_10304, winter_glorad_11502, winter_glorad_20203, 
             summer_glorad_10304, summer_glorad_11502, summer_glorad_20203, ncol = 3)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = glorad, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

# rel. Humidity
``` {r}
summary(lm(hydro_summer_10304$relhum ~ hydro_summer_10304$drainage))
summer_relhum_10304 <- ggplot(hydro_summer_10304, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$relhum ~ hydro_summer_11502$drainage))
summer_relhum_11502 <- ggplot(hydro_summer_11502, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$relhum ~ hydro_summer_20203$drainage))
summer_relhum_20203 <- ggplot(hydro_summer_20203, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_relhum_10304, summer_relhum_11502, summer_relhum_20203, ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = relhum, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
# Winter
summary(lm(hydro_winter_10304$relhum ~ hydro_winter_10304$drainage))
winter_relhum_10304 <- ggplot(hydro_winter_10304, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$relhum ~ hydro_winter_11502$drainage))
winter_relhum_11502 <- ggplot(hydro_winter_11502, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$relhum ~ hydro_winter_20203$drainage))
winter_relhum_20203 <- ggplot(hydro_winter_20203, aes(relhum, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_relhum_10304, winter_relhum_11502, winter_relhum_20203, ncol = 2)
grid.arrange(winter_relhum_10304, winter_relhum_11502, winter_relhum_20203, 
             summer_relhum_10304, summer_relhum_11502, summer_relhum_20203, ncol = 3)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = relhum, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()



```

# Groundwater depth
``` {r}
summary(lm(hydro_summer_10304$groundwaterdepth ~ hydro_summer_10304$drainage))
summer_groundwaterdepth_10304 <- ggplot(hydro_summer_10304, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$groundwaterdepth ~ hydro_summer_11502$drainage))
summer_groundwaterdepth_11502 <- ggplot(hydro_summer_11502, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$groundwaterdepth ~ hydro_summer_20203$drainage))
summer_groundwaterdepth_20203 <- ggplot(hydro_summer_20203, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_groundwaterdepth_10304, summer_groundwaterdepth_11502, summer_groundwaterdepth_20203, ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = groundwaterdepth, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

# Winter
summary(lm(hydro_winter_10304$groundwaterdepth ~ hydro_winter_10304$drainage))
winter_groundwaterdepth_10304 <- ggplot(hydro_winter_10304, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$groundwaterdepth ~ hydro_winter_11502$drainage))
winter_groundwaterdepth_11502 <- ggplot(hydro_winter_11502, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$groundwaterdepth ~ hydro_winter_20203$drainage))
winter_groundwaterdepth_20203 <- ggplot(hydro_winter_20203, aes(groundwaterdepth, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_groundwaterdepth_10304, winter_groundwaterdepth_11502, winter_groundwaterdepth_20203, ncol = 2)
grid.arrange(winter_groundwaterdepth_10304, winter_groundwaterdepth_11502, winter_groundwaterdepth_20203, 
             summer_groundwaterdepth_10304, summer_groundwaterdepth_11502, summer_groundwaterdepth_20203, ncol = 3)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = groundwaterdepth, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

# Soilwater
``` {r}
summary(lm(hydro_summer_10304$soilwater ~ hydro_summer_10304$drainage))
summer_soilwater_10304 <- ggplot(hydro_summer_10304, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$soilwater ~ hydro_summer_11502$drainage))
summer_soilwater_11502 <- ggplot(hydro_summer_11502, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$soilwater ~ hydro_summer_20203$drainage))
summer_soilwater_20203 <- ggplot(hydro_summer_20203, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_soilwater_10304, summer_soilwater_11502, summer_soilwater_20203, ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = soilwater, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

# Winter
summary(lm(hydro_winter_10304$soilwater ~ hydro_winter_10304$drainage))
winter_soilwater_10304 <- ggplot(hydro_winter_10304, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$soilwater ~ hydro_winter_11502$drainage))
winter_soilwater_11502 <- ggplot(hydro_winter_11502, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$soilwater ~ hydro_winter_20203$drainage))
winter_soilwater_20203 <- ggplot(hydro_winter_20203, aes(soilwater, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_soilwater_10304, winter_soilwater_11502, winter_soilwater_20203, ncol = 2)
grid.arrange(winter_soilwater_10304, winter_soilwater_11502, winter_soilwater_20203, 
             summer_soilwater_10304, summer_soilwater_11502, summer_soilwater_20203, ncol = 3)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = soilwater, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

# snow
``` {r}
summary(lm(hydro_summer_10304$snowstorage ~ hydro_summer_10304$drainage))
summer_snowstorage_10304 <-  ggplot(hydro_summer_10304, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_11502$snowstorage ~ hydro_summer_11502$drainage))
summer_snowstorage_11502 <- ggplot(hydro_summer_11502, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_summer_20203$snowstorage ~ hydro_summer_20203$drainage))
summer_snowstorage_20203 <- ggplot(hydro_summer_20203, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(summer_snowstorage_10304, summer_snowstorage_11502, summer_snowstorage_20203, ncol = 2)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_summer_10304, aes(x = snowstorage, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

# Winter
summary(lm(hydro_winter_10304$snowstorage ~ hydro_winter_10304$drainage))
winter_snowstorage_10304 <- ggplot(hydro_winter_10304, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_11502$snowstorage ~ hydro_winter_11502$drainage))
winter_snowstorage_11502 <- ggplot(hydro_winter_11502, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
summary(lm(hydro_winter_20203$snowstorage ~ hydro_winter_20203$drainage))
winter_snowstorage_20203 <- ggplot(hydro_winter_20203, aes(snowstorage, drainage)) +
  geom_point() +
  geom_smooth(method = "lm", formular = y~x)
grid.arrange(winter_snowstorage_10304, winter_snowstorage_11502, winter_snowstorage_20203, ncol = 2)
grid.arrange(winter_snowstorage_10304, winter_snowstorage_11502, winter_snowstorage_20203, 
             summer_snowstorage_10304, summer_snowstorage_11502, summer_snowstorage_20203, ncol = 3)

## Nach membern differenziert ein Testplot
ggplot(data = hydro_winter_10304, aes(x = snowstorage, y = drainage, color = member)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()

```


### ZV: LowLevel

##temp
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TURE) +
                            labs(title = "Summer 10304", x = "Temp", y = "LowLevel")
event_summer_10304_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_10304_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_10304_tmp <- grid.arrange(event_summer_10304_tmp, event_summer_10304_tmp0, event_summer_10304_tmp1, ncol = 1)


y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "Temp", y = "LowLevel")
event_summer_11502_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_11502_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_11502_tmp <- grid.arrange(event_summer_11502_tmp, event_summer_11502_tmp0, event_summer_11502_tmp1, ncol = 1)


y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "Temp", y = "LowLevel")
event_summer_20203_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_20203_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_20203_tmp <- grid.arrange(event_summer_20203_tmp, event_summer_20203_tmp0, event_summer_20203_tmp1, ncol = 1)

grid.arrange(grid_event_summer_10304_tmp, grid_event_summer_11502_tmp, grid_event_summer_20203_tmp, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "Temp", y = "LowLevel")
event_winter_10304_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_10304_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_10304_tmp <- grid.arrange(event_winter_10304_tmp, event_winter_10304_tmp0, event_winter_10304_tmp1, ncol = 1)


y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "Temp", y = "LowLevel")
event_winter_11502_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_11502_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_11502_tmp <- grid.arrange(event_winter_11502_tmp, event_winter_11502_tmp0, event_winter_11502_tmp1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$airtmp
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_tmp <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "Temp", y = "LowLevel")
event_winter_20203_tmp0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_20203_tmp1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_20203_tmp <- grid.arrange(event_winter_20203_tmp, event_winter_20203_tmp0, event_winter_20203_tmp1, ncol = 1)

grid.arrange(grid_event_summer_10304_tmp, grid_event_summer_11502_tmp, grid_event_summer_20203_tmp, ncol = 2)
grid.arrange(grid_event_summer_10304_tmp, grid_event_summer_11502_tmp, grid_event_summer_20203_tmp, grid_event_summer_10304_tmp, grid_event_summer_11502_tmp, grid_event_summer_20203_tmp, ncol = 3)

```

##precip
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "precip", y = "LowLevel")
event_summer_10304_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_10304_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_10304_precip <- grid.arrange(event_summer_10304_precip, event_summer_10304_precip0, event_summer_10304_precip1, ncol = 1)



y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "precip", y = "LowLevel")
event_summer_11502_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_11502_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_11502_precip <- grid.arrange(event_summer_11502_precip, event_summer_11502_precip0, event_summer_11502_precip1, ncol = 1)



y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "precip", y = "LowLevel")
event_summer_20203_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_summer_20203_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_summer_20203_precip <- grid.arrange(event_summer_20203_precip, event_summer_20203_precip0, event_summer_20203_precip1, ncol = 1)
grid.arrange(grid_event_summer_10304_precip, grid_event_summer_11502_precip, grid_event_summer_20203_precip, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "precip", y = "LowLevel")
event_winter_10304_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_10304_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_10304_precip <- grid.arrange(event_winter_10304_precip, event_winter_10304_precip0, event_winter_10304_precip1, ncol = 1)


y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "precip", y = "LowLevel")
event_winter_11502_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_11502_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_11502_precip <- grid.arrange(event_winter_11502_precip, event_winter_11502_precip0, event_winter_11502_precip1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$precip
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_precip <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "precip", y = "LowLevel")
event_winter_20203_precip0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "tmp", y = "Low Level")
event_winter_20203_precip1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "tmp", y = "Low Level")
grid_event_winter_20203_precip <- grid.arrange(event_winter_20203_precip, event_winter_20203_precip0, event_winter_20203_precip1, ncol = 1)
grid.arrange(grid_event_winter_10304_precip, grid_event_winter_11502_precip, grid_event_winter_20203_precip, ncol = 2)
grid.arrange(grid_event_summer_10304_precip, grid_event_summer_11502_precip, grid_event_summer_20203_precip, grid_event_winter_10304_precip, grid_event_winter_11502_precip, grid_event_winter_20203_precip, ncol = 3)

```

## radiation
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_glorad<- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "glorad", y = "LowLevel")
event_summer_10304_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_summer_10304_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_summer_10304_glorad <- grid.arrange(event_summer_10304_glorad, event_summer_10304_glorad0, event_summer_10304_glorad1, ncol = 1)


y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_glorad <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "glorad", y = "LowLevel")
event_summer_11502_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_summer_11502_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_summer_11502_glorad <- grid.arrange(event_summer_11502_glorad, event_summer_11502_glorad0, event_summer_11502_glorad1, ncol = 1)


y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_glorad <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "glorad", y = "LowLevel")
event_summer_20203_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_summer_20203_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_summer_20203_glorad <- grid.arrange(event_summer_20203_glorad, event_summer_20203_glorad0, event_summer_20203_glorad1, ncol = 1)

grid.arrange(grid_event_summer_10304_glorad, grid_event_summer_11502_glorad, grid_event_summer_20203_glorad, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_glorad <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "glorad", y = "LowLevel")
event_winter_10304_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_winter_10304_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_winter_10304_glorad <- grid.arrange(event_winter_10304_glorad, event_winter_10304_glorad0, event_winter_10304_glorad1, ncol = 1)                           


y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_glorad <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "glorad", y = "LowLevel")
event_winter_11502_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_winter_11502_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_winter_11502_glorad <- grid.arrange(event_winter_11502_glorad, event_winter_11502_glorad0, event_winter_11502_glorad1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$glorad
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_glorad <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "glorad", y = "LowLevel")
event_winter_20203_glorad0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "glorad", y = "Low Level")
event_winter_20203_glorad1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "glorad", y = "Low Level")
grid_event_winter_20203_glorad <- grid.arrange(event_winter_20203_glorad, event_winter_20203_glorad0, event_winter_20203_glorad1, ncol = 1)
grid.arrange(grid_event_winter_10304_glorad, grid_event_winter_11502_glorad, grid_event_winter_20203_glorad, ncol = 2)
grid.arrange(grid_event_summer_10304_glorad, grid_event_summer_11502_glorad, grid_event_summer_20203_glorad, grid_event_winter_10304_glorad, grid_event_winter_11502_glorad, grid_event_winter_20203_glorad, ncol = 3)

```

## rel.humidity
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "relhum", y = "LowLevel")
event_summer_10304_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_summer_10304_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_summer_10304_relhum <- grid.arrange(event_summer_10304_relhum, event_summer_10304_relhum0, event_summer_10304_relhum1, ncol = 1)

y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "relhum", y = "LowLevel")
event_summer_11502_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_summer_11502_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_summer_11502_relhum <- grid.arrange(event_summer_11502_relhum, event_summer_11502_relhum0, event_summer_11502_relhum1, ncol = 1)


y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "relhum", y = "LowLevel")
event_summer_20203_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_summer_20203_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_summer_20203_relhum <- grid.arrange(event_summer_20203_relhum, event_summer_20203_relhum0, event_summer_20203_relhum1, ncol = 1)

grid.arrange(grid_event_summer_10304_relhum, grid_event_summer_11502_relhum, grid_event_summer_20203_relhum, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "relhum", y = "LowLevel")
event_winter_10304_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_winter_10304_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_winter_10304_relhum <- grid.arrange(event_winter_10304_relhum, event_winter_10304_relhum0, event_winter_10304_relhum1, ncol = 1)       

y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "relhum", y = "LowLevel")
event_winter_11502_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_winter_11502_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_winter_11502_relhum <- grid.arrange(event_winter_11502_relhum, event_winter_11502_relhum0, event_winter_11502_relhum1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$relhum
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_relhum <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "relhum", y = "LowLevel")
event_winter_20203_relhum0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "relhum", y = "Low Level")
event_winter_20203_relhum1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "relhum", y = "Low Level")
grid_event_winter_20203_relhum <- grid.arrange(event_winter_20203_relhum, event_winter_20203_relhum0, event_winter_20203_relhum1, ncol = 1)

grid.arrange(grid_event_winter_10304_relhum, grid_event_winter_11502_relhum, grid_event_winter_20203_relhum, ncol = 2)
grid.arrange(grid_event_summer_10304_relhum, grid_event_summer_11502_relhum, grid_event_summer_20203_relhum, grid_event_winter_10304_relhum, grid_event_winter_11502_relhum, grid_event_winter_20203_relhum, ncol = 3)


```

## groundwater depth
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "groundwaterdepth", y = "LowLevel")
event_summer_10304_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_summer_10304_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_summer_10304_groundwaterdepth <- grid.arrange(event_summer_10304_groundwaterdepth, event_summer_10304_groundwaterdepth0, event_summer_10304_groundwaterdepth1, ncol = 1)



y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "groundwaterdepth", y = "LowLevel")
event_summer_11502_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_summer_11502_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_summer_11502_groundwaterdepth<- grid.arrange(event_summer_11502_groundwaterdepth, event_summer_11502_groundwaterdepth0, event_summer_11502_groundwaterdepth1, ncol = 1)



y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "groundwaterdepth", y = "LowLevel")
event_summer_20203_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_summer_20203_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_summer_20203_groundwaterdepth <- grid.arrange(event_summer_20203_groundwaterdepth, event_summer_20203_groundwaterdepth0, event_summer_20203_groundwaterdepth1, ncol = 1)

grid.arrange(grid_event_summer_10304_groundwaterdepth, grid_event_summer_11502_groundwaterdepth, grid_event_summer_20203_groundwaterdepth, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "groundwaterdepth", y = "LowLevel")
event_winter_10304_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_winter_10304_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_winter_10304_groundwaterdepth <- grid.arrange(event_winter_10304_groundwaterdepth, event_winter_10304_groundwaterdepth0, event_winter_10304_groundwaterdepth1, ncol = 1)  


y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "groundwaterdepth", y = "LowLevel")
event_winter_11502_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_winter_11502_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_winter_11502_groundwaterdepth <- grid.arrange(event_winter_11502_groundwaterdepth, event_winter_11502_groundwaterdepth0, event_winter_11502_groundwaterdepth1, ncol = 1)



y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$groundwaterdepth
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_groundwaterdepth <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "groundwaterdepth", y = "LowLevel")
event_winter_20203_groundwaterdepth0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "groundwaterdepth", y = "Low Level")
event_winter_20203_groundwaterdepth1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "groundwaterdepth", y = "Low Level")
grid_event_winter_20203_groundwaterdepth <- grid.arrange(event_winter_20203_groundwaterdepth, event_winter_20203_groundwaterdepth0, event_winter_20203_groundwaterdepth1, ncol = 1)

grid.arrange(grid_event_winter_10304_groundwaterdepth, grid_event_winter_11502_groundwaterdepth, grid_event_winter_20203_groundwaterdepth, ncol = 2)
grid.arrange(grid_event_summer_10304_groundwaterdepth, grid_event_summer_11502_groundwaterdepth, grid_event_summer_20203_groundwaterdepth, grid_event_winter_10304_groundwaterdepth, grid_event_winter_11502_groundwaterdepth, grid_event_winter_20203_groundwaterdepth, ncol = 3)


```

##soilwater
``` {r}
# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "soilwater", y = "LowLevel")
event_summer_10304_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_summer_10304_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_summer_10304_soilwater <- grid.arrange(event_summer_10304_soilwater, event_summer_10304_soilwater0, event_summer_10304_soilwater1, ncol = 1)


y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "soilwater", y = "LowLevel")
event_summer_11502_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_summer_11502_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_summer_11502_soilwater <- grid.arrange(event_summer_11502_soilwater, event_summer_11502_soilwater0, event_summer_11502_soilwater1, ncol = 1)


y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "soilwater", y = "LowLevel")
event_summer_20203_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_summer_20203_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_summer_20203_soilwater <- grid.arrange(event_summer_20203_soilwater, event_summer_20203_soilwater0, event_summer_20203_soilwater1, ncol = 1)

grid.arrange(grid_event_summer_10304_soilwater, grid_event_summer_11502_soilwater, grid_event_summer_20203_soilwater, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "soilwater", y = "LowLevel")
event_winter_10304_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_winter_10304_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_winter_10304_soilwater <- grid.arrange(event_winter_10304_soilwater, event_winter_10304_soilwater0, event_winter_10304_soilwater1, ncol = 1)       

y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "soilwater", y = "LowLevel")
event_winter_11502_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_winter_11502_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_winter_11502_soilwater <- grid.arrange(event_winter_11502_soilwater, event_winter_11502_soilwater0, event_winter_11502_soilwater1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$soilwater
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_soilwater <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "soilwater", y = "LowLevel")
event_winter_20203_soilwater0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "soilwater", y = "Low Level")
event_winter_20203_soilwater1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "soilwater", y = "Low Level")
grid_event_winter_20203_soilwater <- grid.arrange(event_winter_20203_soilwater, event_winter_20203_soilwater0, event_winter_20203_soilwater1, ncol = 1)

grid.arrange(grid_event_summer_10304_soilwater, grid_event_summer_11502_soilwater, grid_event_summer_20203_soilwater, ncol = 2)
grid.arrange(grid_event_summer_10304_soilwater, grid_event_summer_11502_soilwater, grid_event_summer_20203_soilwater, grid_event_summer_10304_soilwater, grid_event_summer_11502_soilwater, grid_event_summer_20203_soilwater, ncol = 3)

```

##Snow
``` {r}

# summer

y <- hydro_summer_10304$lowlevel
x <- hydro_summer_10304$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_10304_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 10304", x = "snowstorage", y = "LowLevel")
event_summer_10304_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_summer_10304_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_summer_10304_snowstorage <- grid.arrange(event_summer_10304_snowstorage, event_summer_10304_snowstorage0, event_summer_10304_snowstorage1, ncol = 1)


y <- hydro_summer_11502$lowlevel
x <- hydro_summer_11502$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_11502_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 11502", x = "snowstorage", y = "LowLevel")
event_summer_11502_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_summer_11502_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_summer_11502_snowstorage <- grid.arrange(event_summer_11502_snowstorage, event_summer_11502_snowstorage0, event_summer_11502_snowstorage1, ncol = 1)


y <- hydro_summer_20203$lowlevel
x <- hydro_summer_20203$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_summer_20203_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Summer 20203", x = "snowstorage", y = "LowLevel")
event_summer_20203_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_summer_20203_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_summer_20203_snowstorage <- grid.arrange(event_summer_20203_snowstorage, event_summer_20203_snowstorage0, event_summer_20203_snowstorage1, ncol = 1)

grid.arrange(grid_event_summer_10304_snowstorage, grid_event_summer_11502_snowstorage, grid_event_summer_20203_snowstorage, ncol = 2)

# winter
y <- hydro_winter_10304$lowlevel
x <- hydro_winter_10304$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_10304_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 10304", x = "snowstorage", y = "LowLevel")
event_winter_10304_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_winter_10304_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_winter_10304_snowstorage <- grid.arrange(event_winter_10304_snowstorage, event_winter_10304_snowstorage0, event_winter_10304_snowstorage1, ncol = 1)       

y <- hydro_winter_11502$lowlevel
x <- hydro_winter_11502$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_11502_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 11502", x = "snowstorage", y = "LowLevel")
event_winter_11502_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_winter_11502_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_winter_11502_snowstorage <- grid.arrange(event_winter_11502_snowstorage, event_winter_11502_snowstorage0, event_winter_11502_snowstorage1, ncol = 1)


y <- hydro_winter_20203$lowlevel
x <- hydro_winter_20203$snowstorage
cor(x, y, method = "pearson")
glm(y~x, data = data.frame(x, y), family = binomial())
event_winter_20203_snowstorage <- ggplot(data = data.frame(x, y), aes(x = x , y = y)) +
                            geom_point() +
                            geom_smooth(method = "glm", method.args = list(family = "binomial"), se = TRUE) +
                            labs(title = "Winter 20203", x = "snowstorage", y = "LowLevel")
event_winter_20203_snowstorage0 <- ggplot(data.frame(y, x) %>% filter(y == 0), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 0", x = "snowstorage", y = "Low Level")
event_winter_20203_snowstorage1 <- ggplot(data.frame(y, x) %>% filter(y == 1), aes(x = x, y = y)) +
                            geom_boxplot() +
                            labs(title = "LowLevel = 1", x = "snowstorage", y = "Low Level")
grid_event_winter_20203_snowstorage <- grid.arrange(event_winter_20203_snowstorage, event_winter_20203_snowstorage0, event_winter_20203_snowstorage1, ncol = 1)

grid.arrange(grid_event_summer_10304_snowstorage, grid_event_summer_11502_snowstorage, grid_event_summer_20203_snowstorage, ncol = 2)
grid.arrange(grid_event_summer_10304_snowstorage, grid_event_summer_11502_snowstorage, grid_event_summer_20203_snowstorage, grid_event_summer_10304_snowstorage, grid_event_summer_11502_snowstorage, grid_event_summer_20203_snowstorage, ncol = 3)

```

# Forst plot
``` {r}
## Sommer

varnames <- colnames(hydro_summer_10304)
varnames[15] <- "Lufttemperatur"
varnames[18] <- "Niederschlag"
varnames[16] <- "KurzwelligeStrahlung"
varnames[19] <- "RelativeLuftfeuchte"
varnames[17] <- "Grundwasserstand"
varnames[37] <- "relOberflchennaheBodenfeuchte"
varnames[20] <- "Schneespeicher"
varnames[26] <- "Niedriwasserevent"
varnames[22] <- "Wasserleitfhigkeit"
## 10304
hydro_summer_10304_named <- hydro_summer_10304
colnames(hydro_summer_10304_named) <- varnames
sommer10304GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_summer_10304_named)
#11502
hydro_summer_11502_named <- hydro_summer_11502
colnames(hydro_summer_11502_named) <- varnames
sommer11502GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_summer_11502_named)
#20203
hydro_summer_20203_named <- hydro_summer_20203
colnames(hydro_summer_20203_named) <- varnames
sommer20203GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_summer_20203_named)

##Winter
##10304
hydro_summer_10304_named <- hydro_summer_10304
colnames(hydro_summer_10304_named) <- varnames
winter10304GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_summer_10304_named)
#11502
hydro_winter_11502_named <- hydro_winter_11502
colnames(hydro_winter_11502_named) <- varnames
winter11502GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_winter_11502_named)
#20203
hydro_summer_20203_named <- hydro_summer_20203
colnames(hydro_summer_20203_named) <- varnames
winter20203GLM <- glm(Niedriwasserevent ~ Lufttemperatur + Niederschlag + KurzwelligeStrahlung + RelativeLuftfeuchte + Grundwasserstand + relOberflchennaheBodenfeuchte + Schneespeicher + Wasserleitfhigkeit, family = binomial(link='logit'), data = hydro_summer_20203_named)

all.models <- list()
all.models[[1]] <- sommer10304GLM
all.models[[2]] <- sommer11502GLM
all.models[[3]] <- sommer20203GLM
all.models[[4]] <- winter10304GLM
all.models[[5]] <- winter11502GLM
all.models[[6]] <- winter20203GLM
plot_models(all.models)
p <- last_plot() +
  scale_color_manual(values = c("yellow", "red", "blue","pink", "green", "purple" ), 
                     name = "Gewsser/Halbjahr", 
                     labels = c("Winter Fraenkische Saale Salz",  "Winter Iller Kempten",  "Winter Isar Mittenwald","Sommer Fraenkische Saale Salz", "Sommer Iller Kempten", "Sommer Isar Mittenwald")) +
  theme(legend.title = element_text(size = 12, face = "bold"))+
  ylab("Odds Ratio")

print(p)
```

### Glm - Linear trend over time 
```{r}
model_1 <- glm(lowlevel ~ date  + avg_airtmp + avg_soilwater + avg_precip + avg_precip * avg_soilwater, data = hydro_summer_10304_kbe, family = binomial)
summary(model_1)

model_2 <- glm(lowlevel ~ date  + avg_airtmp + avg_soilwater + avg_precip + avg_precip * avg_soilwater + avg_snowstorage + avg_glorad  + avg_infiltration, data = hydro_summer_10304_kbe, family = binomial)
summary(model_2)

# generalized linear mixed-effects model with random intercept for member (no interactions)
library(lme4)
glmer_1 <- glmer(lowlevel ~ precip + airtmp + glorad + relhum + soilwater + snowstorage + groundwaterdepth + infiltration + (1|member), data = hydro_winter_10304, family = binomial())
summary(glmer_1)
```

# GAM with "normal" drivers
```{r}
library(mgcv)
gam_1 <- gam(lowlevel ~ date + s(avg_airtmp) + s(avg_soilwater) + s(avg_precip) + avg_precip * avg_soilwater + avg_snowstorage + s(avg_glorad) + s(avg_infiltration), data = hydro_summer_10304_kbe, family = binomial(), method = "REML")
summary(gam_1)

gam_1_s_interac <- gam(lowlevel ~ s(precip) + s(airtmp) + s(glorad) + s(relhum) + s(soilwater) + s(snowstorage) + s(groundwaterdepth) + s(infiltration) + s(precip, by = soilwater), data = hydro_summer_10304, family = binomial(), method = "REML")
summary(gam_1_s_interac)
plot(gam_1_s_interac)

## gam mit glatten Effekten (penalized B-splines) und member als random Effekt
# 10304, winter
gam_randinter_member_10304_winter <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_winter_10304, family = binomial(), method = "REML")
summary(gam_randinter_member_10304_winter)
plot(gam_randinter_member_10304_winter)

# 10304, summer
gam_randinter_member_10304_summer <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_summer_10304, family = binomial(), method = "REML")
summary(gam_randinter_member_10304_summer)
plot(gam_randinter_member_10304_summer)

# 11502, winter
gam_randinter_member_11502_winter <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_winter_11502, family = binomial(), method = "REML")
summary(gam_randinter_member_11502_winter)
plot(gam_randinter_member_11502_winter)

# 11502, summer
gam_randinter_member_11502_summer <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_summer_11502, family = binomial(), method = "REML")
summary(gam_randinter_member_11502_summer)
plot(gam_randinter_member_11502_summer)

# 20203, winter
gam_randinter_member_20203_winter <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_winter_20203, family = binomial(), method = "REML")
summary(gam_randinter_member_20203_winter)
plot(gam_randinter_member_20203_winter)

# 20203, summer
gam_randinter_member_20203_summer <- gam(lowlevel ~ date + s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(member, bs = "re"), data = hydro_summer_20203, family = binomial(), method = "REML")
summary(gam_randinter_member_20203_summer)
plot(gam_randinter_member_20203_summer)

gam_randinter_member_ps <- gam(lowlevel ~ s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(precip, by = soilwater, bs = "ps") + s(member, bs = "re"), data = hydro_winter_10304, family = binomial(), method = "REML")
summary(gam_randinter_member_ps)
plot(gam_randinter_member_ps)


# generalized additive mixed model with ARMA-correlation-structure for member kbe
gamm_randinter_member_ps_corAR1 <- gamm(lowlevel ~ s(precip, bs = "ps") + s(airtmp, bs = "ps") + s(glorad, bs = "ps") + s(relhum, bs = "ps") + s(soilwater, bs = "ps") + s(snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(infiltration, bs = "ps") + s(precip, by = soilwater, bs = "ps") + s(member, bs = "re"), data = hydro_winter_10304, family = binomial(), correlation = corCAR1(form = ~ date | member))
# Ausprobieren: corARMA(p = 4, q = 1)
summary(gamm_randinter_member_ps_corAR1)


gam_2 <- gam(lowlevel ~ date + s(airtmp) + s(soilwater) + s(precip) + s(soilwater, precip), data = hydro_summer_10304_kbe, family = binomial())
summary(gam_2)


```

# GAM with avg drivers
```{r}
library(mgcv)

## gam mit avg drivers glatten Effekten (penalized B-splines) fr member kbe
# 10304, winter
gam_memberkbe_avg_10304_winter <- gam(lowlevel ~ date + s(avg_precip, bs = "ps") + s(avg_airtmp, bs = "ps") + s(avg_glorad, bs = "ps") + s(avg_relhum, bs = "ps") + s(avg_soilwater, bs = "ps") + s(avg_snowstorage, bs = "ps") + s(groundwaterdepth, bs = "ps") + s(avg_infiltration, bs = "ps") , data = hydro_winter_10304_kbe, family = binomial(), method = "REML")
summary(gam_memberkbe_avg_10304_winter)
plot(gam_memberkbe_avg_10304_winter)
```

# P Splines
```{r}
gam_1_ps <- gam(lowlevel ~ date  + s(avg_airtmp, bs = "ps") + s(avg_soilwater, bs = "ps") + s(avg_precip, bs = "ps") + avg_precip * avg_soilwater + avg_snowstorage + s(avg_glorad, bs = "ps")  + s(avg_infiltration, bs = "ps"), data = hydro_summer_10304_kbe, family = binomial(), method = "REML")
summary(gam_1_ps)

gam_2_ps <- gam(lowlevel ~ date + s(airtmp, bs = "ps") + s(soilwater, bs = "ps") + s(precip, bs = "ps") + s(soilwater, by = precip, bs = "ps"), data = hydro_summer_10304_kbe, family = binomial())

summary(gam_2_ps)
```

# ARIMA-Models
```{r}
library(forecast)

model_Arima <- Arima(hydro_winter_10304_kbe$lowlevel,xreg = as.matrix(subset(hydro_winter_10304_kbe, select = c(precip, airtmp, glorad, relhum, soilwater, snowstorage, groundwaterdepth, infiltration))), order = c(4, 0, 7))
summary(model_Arima)

acf(resid(model_Arima))
```

https://online.stat.psu.edu/stat501/book/export/html/996#:~:text=The%20order%20of%20an%20autoregression,written%20as%20AR(1)
# Lag DF
```{r}
lag_df <- function(dat, lag) {
  data.frame(unclass(dat[c(rep(NA, lag), 1:(nrow(dat)-lag)),]))
}

ggplot(aes(x = (lag(hydro_summer_10304_kbe$airtmp, 3)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$soilwater, 2)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$precip, 2)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$avg_precip, 0)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)
```

# ARDLM
```{r}
ardlDlm_1 <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp + glorad, data = hydro_summer_10304_kbe, p = 2, q = 2)

summary(ardlDlm_1)
```


```{r}

results_ardldlm_10304 <- list()
i <- 1
for (member in unique(hydro_summer_10304$member)){
  data <- hydro_summer_10304[hydro_summer_10304["member"] == member,]
  results_ardldlm_10304[i] <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp, data = data, p = 3, q = 2)
  i <- i+ 1
}

lapply(results_ardldlm_10304, summary)

```
```{r}
results_ardldlm_11502 <- list()
i <- 1
for (member in unique(hydro_summer_10304$member)){
  data <- hydro_summer_11502[hydro_summer_11502["member"] == member,]
  results_ardldlm_11502[i] <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp, data = data, p = 3, q = 2)
  i <- i+ 1
}

lapply(results_ardldlm_11502, summary)
```

```{r}
fit_ardlm_across <- function(formula, data, p, q, summary_output = TRUE) {
  results <- list()
i <- 1
for (member in unique(data$member)){
  data_loop <- data[data["member"] == member,]
  results[i] <- ardlDlm(formula = formula, data = data_loop, p = p, q = q)
  i <- i+ 1
}

lapply(results, summary)
}
```
# Summer
```{r}
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_10304, p = 3, q = 4)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_11502, p = 3, q = 4)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp + glorad, data = hydro_summer_20203, p = 3, q = 4)


lapply(fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_20203, p = 2, q = 2), "[[", "adj.r.squared")
```
# Winter
```{r}
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_10304, p = 3, q = 2)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_11502, p = 3, q = 2)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_20203, p = 3, q = 2)
```
```