---
title: "Data Preperation"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
# Import packages
library(tidyverse)
```

## Data import

```{r Data import}
pegel_eigen <- read_csv2(file = "data/Geo-Daten_Uebersicht/Eigenschaften_Pegel.csv")
pegel_eigen <- read.csv2("data/Geo-Daten_Uebersicht/Eigenschaften_Pegel.csv")
hydro_summer <- read.table("data/Zielvariablen/hydro_summer.txt")
hydro_winter <- read.table("data/Zielvariablen/hydro_winter.txt")

pegel_ids <- c("20203", "11502", "10304")
names(pegel_ids) <- c("PEG-Fraenkische-Saale-Salz", "PEG-Iller-Kempten", "PEG-Isar-Mittenwald")
pegel_ids_list <- list("20203", "11502", "10304")
names(pegel_ids_list) <- c("Fraenkische Saale Salz", "Iller Kempten", "Isar Mittenwald")
```

## Overview

```{r Overview, echo=FALSE}
hydro_summer %>% count(member, sort = TRUE)
hydro_winter %>% count(member, sort = TRUE)
head(pegel_eigen)
head(hydro_summer)
head(hydro_winter)
unique(hydro_summer$slope)
```

## Data Manipulation

```{r}
# Remove index row for pegel_eigen
pegel_eigen  <- pegel_eigen[-1]

# Filter for our 3 waterlevel
pegel_prop <- pegel_eigen %>% filter(ID %in% pegel_ids)

# Change name_waterlevel
hydro_summer$name_waterlevel <- sub('.', '', hydro_summer$name_waterlevel)
hydro_winter$name_waterlevel <- sub('.', '', hydro_winter$name_waterlevel)

hydro_summer$name_waterlevel <- as.factor(hydro_summer$name_waterlevel)
hydro_winter$name_waterlevel <- as.factor(hydro_winter$name_waterlevel)

hydro_summer$waterlevel <- hydro_summer$name_waterlevel
levels(hydro_summer$waterlevel) <- pegel_ids_list
hydro_winter$waterlevel <- hydro_winter$name_waterlevel
levels(hydro_winter$waterlevel) <- pegel_ids_list

# Adjust data types
hydro_summer$date <- as.Date(hydro_summer$date)
hydro_winter$date <- as.Date(hydro_winter$date)

hydro_summer$member <- as.factor(hydro_summer$member)
hydro_winter$member <- as.factor(hydro_winter$member)

hydro_summer$river <- as.factor(hydro_summer$river)
hydro_winter$river <- as.factor(hydro_winter$river)

hydro_summer$landuse <- as.factor(hydro_summer$landuse)
hydro_winter$landuse <- as.factor(hydro_winter$landuse)

hydro_summer$exposition <- as.factor(hydro_summer$exposition)
hydro_winter$exposition <- as.factor(hydro_winter$exposition)

hydro_summer$lowlevel_1d <- as.factor(hydro_summer$lowlevel_1d)
levels(hydro_summer$lowlevel_1d) <- c(FALSE, TRUE)
hydro_winter$lowlevel_1d <- as.factor(hydro_winter$lowlevel_1d)
levels(hydro_winter$lowlevel_1d) <- c(FALSE, TRUE)
hydro_summer$lowlevel <- as.factor(hydro_summer$lowlevel)
levels(hydro_summer$lowlevel) <- c(FALSE, TRUE)
hydro_winter$lowlevel <- as.factor(hydro_winter$lowlevel)
levels(hydro_winter$lowlevel) <- c(FALSE, TRUE)

hydro_summer$hydro_year <- as.factor(hydro_summer$hydro_year)
hydro_winter$hydro_year <- as.factor(hydro_winter$hydro_year)

# Create hydro total
hydro_total <- rbind(hydro_summer, hydro_winter)
```

## Adjustments
```{r Data manipulation}
# Add rescaled soilwater
hydro_summer$soilwater100 <- hydro_summer$soilwater * 100
hydro_winter$soilwater100 <- hydro_winter$soilwater * 100

## add column max_precip
# winter
max_precip <- as.numeric(rep(NA, length = nrow(hydro_winter)))
for(k in 7:length(max_precip)) {
  if (all(hydro_winter$member[(k - 6):(k - 1)] == hydro_winter$member[k]) &&
      all(hydro_winter$name_waterlevel[(k - 6):(k - 1)] == hydro_winter$name_waterlevel[k])) {
    if (hydro_winter$MM[k] == 11) {
      if (all(hydro_winter$MM[(k - 6):(k - 1)] == 11)) {
        max_precip[k] <- max(hydro_winter$precip[(k - 6):k])
      }
    } else {
    max_precip[k] <- max(hydro_winter$precip[(k - 6):k])
    }
  }
}
hydro_winter <- cbind(hydro_winter, max_precip)

# summer
max_precip <- as.numeric(rep(NA, length = nrow(hydro_summer)))
for(k in 7:length(max_precip)) {
  if (all(hydro_summer$member[(k - 6):(k - 1)] == hydro_summer$member[k]) &&
      all(hydro_summer$name_waterlevel[(k - 6):(k - 1)] == hydro_summer$name_waterlevel[k])) {
    if (hydro_summer$MM[k] == 5) {
      if (all(hydro_summer$MM[(k - 6):(k - 1)] == 5)) {
        max_precip[k] <- max(hydro_summer$precip[(k - 6):k])
      }
    } else {
    max_precip[k] <- max(hydro_summer$precip[(k - 6):k])
    }
  }
}
hydro_summer <- cbind(hydro_summer, max_precip)

##Rescaling
hydro_winter$max_precip_scaled <- hydro_winter$max_precip * 1.25
hydro_summer$max_precip_scaled <- hydro_summer$max_precip * 1.25


# add column snowstorage_diff
# winter
snowstorage_diff <- as.numeric(rep(NA, length = nrow(hydro_winter)))
for(k in 2:length(snowstorage_diff)) {
  if (hydro_winter$member[k - 1] == hydro_winter$member[k] &&
      hydro_winter$name_waterlevel[k - 1] == hydro_winter$name_waterlevel[k]) {
    if(!any(is.na(hydro_winter$snowstorage[(k - 1):k]))) {
      if (hydro_winter$MM[k] == 11) {
        if (hydro_winter$MM[k - 1] == 11) {
          snowstorage_diff[k] <- hydro_winter$snowstorage[k] - hydro_winter$snowstorage[k - 1]
        }
      } else {
        snowstorage_diff[k] <- hydro_winter$snowstorage[k] - hydro_winter$snowstorage[k - 1]
      }
    }
  }
}
hydro_winter <- cbind(hydro_winter, snowstorage_diff) 

# summer
snowstorage_diff <- as.numeric(rep(NA, length = nrow(hydro_summer)))
for(k in 2:length(snowstorage_diff)) {
  if (hydro_summer$member[k - 1] == hydro_summer$member[k] &&
      hydro_summer$name_waterlevel[k - 1] == hydro_summer$name_waterlevel[k]) {
    if(!any(is.na(hydro_summer$snowstorage[(k - 1):k]))) {
      if (hydro_summer$MM[k] == 5) {
        if (hydro_summer$MM[k - 1] == 5) {
          snowstorage_diff[k] <- hydro_summer$snowstorage[k] - hydro_summer$snowstorage[k - 1]
        }
      } else {
        snowstorage_diff[k] <- hydro_summer$snowstorage[k] - hydro_summer$snowstorage[k - 1]
      }
    }
  }
}
hydro_summer <- cbind(hydro_summer, snowstorage_diff)


# add column snowstorage_drain
# winter
hydro_winter$snowstorage_drain <- hydro_winter$snowstorage_diff
for (k in 1:length(hydro_winter$snowstorage_drain)) {
  if (!is.na(hydro_winter$snowstorage_diff[k])) {
    if (hydro_winter$snowstorage_diff[k] < 0) {
      hydro_winter$snowstorage_drain[k] <- abs(hydro_winter$snowstorage_drain[k])
    } else if (hydro_winter$snowstorage_diff[k] >= 0) {
      hydro_winter$snowstorage_drain[k] <- 0
    }
  }
}

# summer
hydro_summer$snowstorage_drain <- hydro_summer$snowstorage_diff
for (k in 1:length(hydro_summer$snowstorage_drain)) {
  if (!is.na(hydro_summer$snowstorage_diff[k])) {
    if (hydro_summer$snowstorage_diff[k] < 0) {
      hydro_summer$snowstorage_drain[k] <- abs(hydro_summer$snowstorage_drain[k])
    } else if (hydro_summer$snowstorage_diff[k] >= 0) {
      hydro_summer$snowstorage_drain[k] <- 0
    }
  }
}

# add column avg_snowstorage_drain
# winter
avg_snowstorage_drain <- as.numeric(rep(NA, length = nrow(hydro_winter)))
for(k in 7:length(avg_snowstorage_drain)) {
  if (all(hydro_winter$member[(k - 6):(k - 1)] == hydro_winter$member[k]) &&
      all(hydro_winter$name_waterlevel[(k - 6):(k - 1)] == hydro_winter$name_waterlevel[k])) {
    if (hydro_winter$MM[k] == 11) {
      if (all(hydro_winter$MM[(k - 6):(k - 1)] == 11)) {
        avg_snowstorage_drain[k] <- mean(hydro_winter$snowstorage_drain[(k - 6):k], na.rm = TRUE)
      }
    } else {
      avg_snowstorage_drain[k] <- mean(hydro_winter$snowstorage_drain[(k - 6):k], na.rm = TRUE)
    }
  }
}
hydro_winter <- cbind(hydro_winter, avg_snowstorage_drain) 

# summer
avg_snowstorage_drain <- as.numeric(rep(NA, length = nrow(hydro_summer)))
for(k in 7:length(avg_snowstorage_drain)) {
  if (all(hydro_summer$member[(k - 6):(k - 1)] == hydro_summer$member[k]) &&
      all(hydro_summer$name_waterlevel[(k - 6):(k - 1)] == hydro_summer$name_waterlevel[k])) {
    if (hydro_summer$MM[k] == 5) {
      if (all(hydro_summer$MM[(k - 6):(k - 1)] == 5)) {
        avg_snowstorage_drain[k] <- mean(hydro_summer$snowstorage_drain[(k - 6):k], na.rm = TRUE)
      }
    } else {
      avg_snowstorage_drain[k] <- mean(hydro_summer$snowstorage_drain[(k - 6):k], na.rm = TRUE)
    }
  }
}
hydro_summer <- cbind(hydro_summer, avg_snowstorage_drain) 


## add column lowlevel_first
# winter
lowlevel_first <- as.numeric(rep(NA, length = nrow(hydro_winter)))
for(k in 1:length(lowlevel_first)) {
  if (!is.na(hydro_winter$lowlevel_days[k])) {
    if (hydro_winter$lowlevel_days[k] == 1) {
      lowlevel_first[k] <- TRUE
    } else {
      lowlevel_first[k] <- FALSE
    }
  }
}
hydro_winter <- cbind(hydro_winter, lowlevel_first) 


# summer
lowlevel_first <- as.numeric(rep(NA, length = nrow(hydro_summer)))
for(k in 1:length(lowlevel_first)) {
  if (!is.na(hydro_summer$lowlevel_days[k])) {
    if (hydro_summer$lowlevel_days[k] == 1) {
      lowlevel_first[k] <- TRUE
    } else {
      lowlevel_first[k] <- FALSE
    }
  }
}
hydro_summer <- cbind(hydro_summer, lowlevel_first) 




# Create subsets for hydrological half-year for each waterlevel
hydro_summer_20203 <- hydro_summer %>% filter(name_waterlevel == "20203")
hydro_summer_11502 <- hydro_summer %>% filter(name_waterlevel == "11502")
hydro_summer_10304 <- hydro_summer %>% filter(name_waterlevel == "10304")
hydro_winter_20203 <- hydro_winter %>% filter(name_waterlevel == "20203")
hydro_winter_11502 <- hydro_winter %>% filter(name_waterlevel == "11502")
hydro_winter_10304 <- hydro_winter %>% filter(name_waterlevel == "10304")


##Rescaling avg Variables
hydro_summer_10304$avg_soilwater_scaled <- hydro_summer_10304$avg_soilwater * 6
hydro_summer_10304$avg_snowstorage_scaled <- hydro_summer_10304$avg_snowstorage * 2
hydro_summer_10304$avg_airtmp_scaled <- hydro_summer_10304$avg_airtmp * 3
hydro_summer_10304$avg_precip_scaled <- hydro_summer_10304$avg_precip * 4.5
hydro_summer_10304$avg_glorad_scaled <- hydro_summer_10304$avg_glorad * 0.062
hydro_summer_10304$avg_relhum_scaled<- hydro_summer_10304$avg_relhum * 1.4
hydro_summer_10304$avg_infiltration_scaled <- hydro_summer_10304$avg_infiltration * 43


hydro_summer_11502$avg_soilwater_scaled <- hydro_summer_11502$avg_soilwater * 6
hydro_summer_11502$avg_snowstorage_scaled <- hydro_summer_11502$avg_snowstorage * 2
hydro_summer_11502$avg_airtmp_scaled <- hydro_summer_11502$avg_airtmp * 3
hydro_summer_11502$avg_precip_scaled <- hydro_summer_11502$avg_precip  * 4.5
hydro_summer_11502$avg_glorad_scaled <- hydro_summer_11502$avg_glorad * 0.062
hydro_summer_11502$avg_relhum_scaled <- hydro_summer_11502$avg_relhum * 1.4
hydro_summer_11502$avg_infiltration_scaled <- hydro_summer_11502$avg_infiltration * 43


hydro_summer_20203$avg_soilwater_scaled <- hydro_summer_20203$avg_soilwater * 6
hydro_summer_20203$avg_snowstorage_scaled <- hydro_summer_20203$avg_snowstorage * 2
hydro_summer_20203$avg_airtmp_scaled <- hydro_summer_20203$avg_airtmp * 3
hydro_summer_20203$avg_precip_scaled <- hydro_summer_20203$avg_precip * 4.5
hydro_summer_20203$avg_glorad_scaled <- hydro_summer_20203$avg_glorad * 0.062
hydro_summer_20203$avg_relhum_scaled <- hydro_summer_20203$avg_relhum * 1.4
hydro_summer_20203$avg_infiltration_scaled <- hydro_summer_20203$avg_infiltration * 43


hydro_winter_10304$avg_soilwater_scaled <- hydro_winter_10304$avg_soilwater * 6
hydro_winter_10304$avg_snowstorage_scaled <- hydro_winter_10304$avg_snowstorage * 2
hydro_winter_10304$avg_airtmp_scaled <- hydro_winter_10304$avg_airtmp * 3
hydro_winter_10304$avg_precip_scaled <- hydro_winter_10304$avg_precip * 4.5
hydro_winter_10304$avg_glorad_scaled <- hydro_winter_10304$avg_glorad * 0.062
hydro_winter_10304$avg_relhum_scaled <- hydro_winter_10304$avg_relhum * 1.4
hydro_winter_10304$avg_infiltration_scaled <- hydro_winter_10304$avg_infiltration * 43


hydro_winter_11502$avg_soilwater_scaled <- hydro_winter_11502$avg_soilwater * 6
hydro_winter_11502$avg_snowstorage_scaled <- hydro_winter_11502$avg_snowstorage * 2
hydro_winter_11502$avg_airtmp_scaled <- hydro_winter_11502$avg_airtmp * 3
hydro_winter_11502$avg_precip_scaled <- hydro_winter_11502$avg_precip  * 4.5
hydro_winter_11502$avg_glorad_scaled <- hydro_winter_11502$avg_glorad * 0.062
hydro_winter_11502$avg_relhum_scaled <- hydro_winter_11502$avg_relhum * 1.4
hydro_winter_11502$avg_infiltration_scaled <- hydro_winter_11502$avg_infiltration * 43


hydro_winter_11502$avg_soilwater_scaled <- hydro_winter_11502$avg_soilwater * 6
hydro_winter_11502$avg_snowstorage_scaled <- hydro_winter_11502$avg_snowstorage * 2
hydro_winter_11502$avg_airtmp_scaled <- hydro_winter_11502$avg_airtmp * 3
hydro_winter_11502$avg_precip_scaled <- hydro_winter_11502$avg_precip * 4.5
hydro_winter_11502$avg_glorad_scaled <- hydro_winter_11502$avg_glorad * 0.062
hydro_winter_11502$avg_relhum_scaled <- hydro_winter_11502$avg_relhum * 1.4
hydro_winter_11502$avg_infiltration_scaled <- hydro_winter_11502$avg_infiltration * 43


# separate datasets for each waterlevel, season and member
# winter, 10304
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_winter_10304", "_", j), hydro_winter_10304 %>% filter(member %in% j))
}

# summer, 10304
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_summer_10304", "_", j), hydro_summer_10304 %>% filter(member %in% j))
}

# winter, 11502
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_winter_11502", "_", j), hydro_winter_11502 %>% filter(member %in% j))
}

# summer, 11502
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_summer_11502", "_", j), hydro_summer_11502 %>% filter(member %in% j))
}

# winter, 20203
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_winter_20203", "_", j), hydro_winter_20203 %>% filter(member %in% j))
}

# summer, 20203
for (j in levels(hydro_total$member)) {
  assign(paste0("hydro_summer_20203", "_", j), hydro_summer_20203 %>% filter(member %in% j))
}
```


## Save data

```{r}
# Save pegel_prop
saveRDS(object = pegel_prop, file = "data/pegel_prop.RDS")

# Save hydro total
saveRDS(object = hydro_total, file = "data/hydro_total.RDS")

# Save hydrological half years
saveRDS(object = hydro_summer, file = "data/hydro_summer.RDS")
saveRDS(object = hydro_winter, file = "data/hydro_winter.RDS")

# Save subsets for hydrological half-year for each waterlevel
saveRDS(object = hydro_summer_20203, file = "data/hydro_summer_20203.RDS")
saveRDS(object = hydro_summer_11502, file = "data/hydro_summer_11502.RDS")
saveRDS(object = hydro_summer_10304, file = "data/hydro_summer_10304.RDS")
saveRDS(object = hydro_winter_20203, file = "data/hydro_winter_20203.RDS")
saveRDS(object = hydro_winter_11502, file = "data/hydro_winter_11502.RDS")
saveRDS(object = hydro_winter_10304, file = "data/hydro_winter_10304.RDS")

# Save subsets for each member, each hydrological half-year and for each waterlevel
saveRDS(object = hydro_summer_20203_kbe, file = "data/hydro_summer_20203_kbe.RDS")
saveRDS(object = hydro_summer_20203_kbj, file = "data/hydro_summer_20203_kbj.RDS")
saveRDS(object = hydro_summer_20203_kbo, file = "data/hydro_summer_20203_kbo.RDS")
saveRDS(object = hydro_summer_20203_kbt, file = "data/hydro_summer_20203_kbt.RDS")
saveRDS(object = hydro_summer_20203_kby, file = "data/hydro_summer_20203_kby.RDS")
saveRDS(object = hydro_summer_20203_kcd, file = "data/hydro_summer_20203_kcd.RDS")
saveRDS(object = hydro_summer_20203_kci, file = "data/hydro_summer_20203_kci.RDS")
saveRDS(object = hydro_summer_20203_kcn, file = "data/hydro_summer_20203_kcn.RDS")
saveRDS(object = hydro_summer_20203_kcs, file = "data/hydro_summer_20203_kcs.RDS")
saveRDS(object = hydro_summer_20203_kcx, file = "data/hydro_summer_20203_kcx.RDS")

saveRDS(object = hydro_summer_11502_kbe, file = "data/hydro_summer_11502_kbe.RDS")
saveRDS(object = hydro_summer_11502_kbj, file = "data/hydro_summer_11502_kbj.RDS")
saveRDS(object = hydro_summer_11502_kbo, file = "data/hydro_summer_11502_kbo.RDS")
saveRDS(object = hydro_summer_11502_kbt, file = "data/hydro_summer_11502_kbt.RDS")
saveRDS(object = hydro_summer_11502_kby, file = "data/hydro_summer_11502_kby.RDS")
saveRDS(object = hydro_summer_11502_kcd, file = "data/hydro_summer_11502_kcd.RDS")
saveRDS(object = hydro_summer_11502_kci, file = "data/hydro_summer_11502_kci.RDS")
saveRDS(object = hydro_summer_11502_kcn, file = "data/hydro_summer_11502_kcn.RDS")
saveRDS(object = hydro_summer_11502_kcs, file = "data/hydro_summer_11502_kcs.RDS")
saveRDS(object = hydro_summer_11502_kcx, file = "data/hydro_summer_11502_kcx.RDS")

saveRDS(object = hydro_summer_10304_kbe, file = "data/hydro_summer_10304_kbe.RDS")
saveRDS(object = hydro_summer_10304_kbj, file = "data/hydro_summer_10304_kbj.RDS")
saveRDS(object = hydro_summer_10304_kbo, file = "data/hydro_summer_10304_kbo.RDS")
saveRDS(object = hydro_summer_10304_kbt, file = "data/hydro_summer_10304_kbt.RDS")
saveRDS(object = hydro_summer_10304_kby, file = "data/hydro_summer_10304_kby.RDS")
saveRDS(object = hydro_summer_10304_kcd, file = "data/hydro_summer_10304_kcd.RDS")
saveRDS(object = hydro_summer_10304_kci, file = "data/hydro_summer_10304_kci.RDS")
saveRDS(object = hydro_summer_10304_kcn, file = "data/hydro_summer_10304_kcn.RDS")
saveRDS(object = hydro_summer_10304_kcs, file = "data/hydro_summer_10304_kcs.RDS")
saveRDS(object = hydro_summer_10304_kcx, file = "data/hydro_summer_10304_kcx.RDS")

saveRDS(object = hydro_winter_20203_kbe, file = "data/hydro_winter_20203_kbe.RDS")
saveRDS(object = hydro_winter_20203_kbj, file = "data/hydro_winter_20203_kbj.RDS")
saveRDS(object = hydro_winter_20203_kbo, file = "data/hydro_winter_20203_kbo.RDS")
saveRDS(object = hydro_winter_20203_kbt, file = "data/hydro_winter_20203_kbt.RDS")
saveRDS(object = hydro_winter_20203_kby, file = "data/hydro_winter_20203_kby.RDS")
saveRDS(object = hydro_winter_20203_kcd, file = "data/hydro_winter_20203_kcd.RDS")
saveRDS(object = hydro_winter_20203_kci, file = "data/hydro_winter_20203_kci.RDS")
saveRDS(object = hydro_winter_20203_kcn, file = "data/hydro_winter_20203_kcn.RDS")
saveRDS(object = hydro_winter_20203_kcs, file = "data/hydro_winter_20203_kcs.RDS")
saveRDS(object = hydro_winter_20203_kcx, file = "data/hydro_winter_20203_kcx.RDS")

saveRDS(object = hydro_winter_11502_kbe, file = "data/hydro_winter_11502_kbe.RDS")
saveRDS(object = hydro_winter_11502_kbj, file = "data/hydro_winter_11502_kbj.RDS")
saveRDS(object = hydro_winter_11502_kbo, file = "data/hydro_winter_11502_kbo.RDS")
saveRDS(object = hydro_winter_11502_kbt, file = "data/hydro_winter_11502_kbt.RDS")
saveRDS(object = hydro_winter_11502_kby, file = "data/hydro_winter_11502_kby.RDS")
saveRDS(object = hydro_winter_11502_kcd, file = "data/hydro_winter_11502_kcd.RDS")
saveRDS(object = hydro_winter_11502_kci, file = "data/hydro_winter_11502_kci.RDS")
saveRDS(object = hydro_winter_11502_kcn, file = "data/hydro_winter_11502_kcn.RDS")
saveRDS(object = hydro_winter_11502_kcs, file = "data/hydro_winter_11502_kcs.RDS")
saveRDS(object = hydro_winter_11502_kcx, file = "data/hydro_winter_11502_kcx.RDS")

saveRDS(object = hydro_winter_10304_kbe, file = "data/hydro_winter_10304_kbe.RDS")
saveRDS(object = hydro_winter_10304_kbj, file = "data/hydro_winter_10304_kbj.RDS")
saveRDS(object = hydro_winter_10304_kbo, file = "data/hydro_winter_10304_kbo.RDS")
saveRDS(object = hydro_winter_10304_kbt, file = "data/hydro_winter_10304_kbt.RDS")
saveRDS(object = hydro_winter_10304_kby, file = "data/hydro_winter_10304_kby.RDS")
saveRDS(object = hydro_winter_10304_kcd, file = "data/hydro_winter_10304_kcd.RDS")
saveRDS(object = hydro_winter_10304_kci, file = "data/hydro_winter_10304_kci.RDS")
saveRDS(object = hydro_winter_10304_kcn, file = "data/hydro_winter_10304_kcn.RDS")
saveRDS(object = hydro_winter_10304_kcs, file = "data/hydro_winter_10304_kcs.RDS")
saveRDS(object = hydro_winter_10304_kcx, file = "data/hydro_winter_10304_kcx.RDS")


```