---
title: "Data analysis"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
# Import packages
library(tidyverse)
library(lubridate)
library(timetk)
library(RcppRoll)
library(dLagM)
library(dlnm)
library(zoo)
# Mapping imports
library(sf)
library(leaflet)
library(tmap)
tmap_options(check.and.fix = TRUE)

# Read data
hydro_summer_20203 <- readRDS(file = "./data/hydro_summer_20203.RDS")
hydro_summer_11502 <- readRDS(file = "./data/hydro_summer_11502.RDS")
hydro_summer_10304 <- readRDS(file = "./data/hydro_summer_10304.RDS")
hydro_winter_20203 <- readRDS(file = "./data/hydro_winter_20203.RDS")
hydro_winter_11502 <- readRDS(file = "./data/hydro_winter_11502.RDS")
hydro_winter_10304 <- readRDS(file = "./data/hydro_winter_10304.RDS")
pegel_prop <- readRDS(file = "./data/pegel_prop.RDS")
```

## Geo Data (Map data)
```{r}
# Read in shape file
hydro_bavaria <- read_sf("./data/Geo-Daten_Uebersicht/shapefile/EZG_OHNE_Reservoir_UTM32.shp", ) 
st_crs(hydro_bavaria) # CRS WGS 84 

# Quelle Data https://hub.arcgis.com/datasets/esri-de-content::bundesl%C3%A4nder-2021-mit-einwohnerzahl/explore?location=51.947250%2C15.358806%2C5.85&showTable=true 
admin_bavaria <- read_sf("./added_data/LAN_ew_21.shp") %>% filter(GEN %in% c("Bayern", "Bayern (Bodensee)"))
admin_bavaria <- st_as_sf(admin_bavaria, crs = 4326)
pegel_prop_sf <- st_as_sf(pegel_prop, coords = c("longitude", "latitude"), crs = 4326) # crs Code for WGS 84

pegel_prop_sf$ID <- as.factor(pegel_prop_sf$ID)

# https://geoportal.bafg.de/CSWView/od.xhtml
waterways <- read_sf("./added_data/germany-waterways-shape/waterways.shp") 

waterways_three <- waterways %>% 
filter(name %in% c("Isar",
                   "Donau", 
                   "Fränkische Saale",
                   "Main",
                   "Iller"))

# Add Pegel props
hydro_bavaria_20203 <- hydro_bavaria %>% filter(gridcode == 20203) %>% 
  left_join(pegel_prop, by = c("gridcode" = "ID"))
hydro_bavaria_11502 <- hydro_bavaria %>% filter(gridcode == 11502)%>% 
  left_join(pegel_prop, by = c("gridcode" = "ID"))
hydro_bavaria_10304 <- hydro_bavaria %>% filter(gridcode == 10304)%>% 
  left_join(pegel_prop, by = c("gridcode" = "ID"))
hydro_bavaria_three <- hydro_bavaria %>% filter(gridcode %in% c(10304, 11502, 20203))%>% 
  left_join(pegel_prop, by = c("gridcode" = "ID"))

```

## Chris: Analysis

```{r Chris analysis}
# First visualizations
plot_dranage <- function(dataset, year = c(2000), member_input = "kbe") {
  dataset %>% filter(YY %in% year, member == member_input) %>%
  ggplot(mapping = aes(x = date, y = drainage, color = waterlevel)) +
    geom_line() +
    scale_y_continuous(trans='log10') +
    geom_point(data = dataset %>% filter(YY %in% year, member == member_input, lowlevel == TRUE), 
               aes(x = date, y = drainage), color = "purple") +
    labs(title = "Drainage für unterschiedliche Pegel über die Zeit",
       y = "Drainage",
       x = "Datum")
}

plot_single_dranage <- function(dataset, year = c(2000), member_input = "kbe") {
  dataset %>% filter(YY %in% year, member == member_input) %>%
  ggplot(mapping = aes(x = date, y = drainage)) +
    geom_line() +
    scale_y_continuous(trans='log10') +
    geom_line(mapping = aes(y = nm7q), color = "red") +
    geom_point(data = dataset %>% filter(YY %in% year, member == member_input, lowlevel == TRUE), 
               aes(x = date, y = drainage), color = "purple") +
    labs(title = "Drainage für einen Pegel über die Zeit",
       y = "Drainage",
       x = "Datum")
}
plot_single_dranage(hydro_total %>% filter(name_waterlevel == "10304"), year = 2000:2003)
ggsave("Plots/Chris/analysis/single_dranage_Isar-Mittenwald_2000-2003.png", width = 12, height = 6)

plot_dranage(hydro_total, year = 2000)
ggsave("Plots/Chris/analysis/dranage_total_2000.png", width = 12, height = 6)


# Tables for futher plots
table_days_low_flow <- hydro_total %>%
  group_by(waterlevel, YY) %>%
  count(lowlevel, name = "number_low_flows") %>%
  filter(lowlevel == TRUE) %>%
  mutate(avg_number_low_flows = number_low_flows / length(unique(hydro_total$member)))

table_days_low_flow_by_hydro_year <- hydro_total %>%
  group_by(hydro_year, waterlevel, YY) %>%
  count(lowlevel, name = "number_low_flows") %>%
  filter(lowlevel == TRUE) %>%
  mutate(avg_number_low_flows = number_low_flows / length(unique(hydro_total$member)))

table_days_low_flow_summer <- hydro_summer %>%
  group_by(waterlevel, YY) %>%
  count(lowlevel, name = "number_low_flows") %>%
  filter(lowlevel == TRUE) %>%
  mutate(avg_number_low_flows = number_low_flows / length(unique(hydro_total$member)))

table_days_low_flow_winter <- hydro_winter %>%
  group_by(waterlevel, YY) %>%
  count(lowlevel, name = "number_low_flows") %>%
  filter(lowlevel == TRUE) %>%
  mutate(avg_number_low_flows = number_low_flows / length(unique(hydro_total$member)))

# Yearly average number of low flow days over time for the 3 waterlevels
ggplot(data = table_days_low_flow, mapping = aes(x = YY, y = avg_number_low_flows, color = waterlevel)) +
  geom_line() +
  geom_point() +
  labs(title = "Jährliche durchschnittliche Anzahl von Niedrigwasser-Tagen im Zeitverlauf",
       y = "Jährliche durchschnittliche Anzahl von Niedrigwasser-Tagen",
       x = "Datum")
ggsave("Plots/Chris/analysis/yearly_avg_number_of_low_flow_days.png", width = 12, height = 6)

ggplot(data = table_days_low_flow_by_hydro_year, mapping = aes(x = YY, y = avg_number_low_flows, color = waterlevel)) +
  geom_line() +
  geom_point() +
  labs(title = "Jährliche durchschnittliche Anzahl von Niedrigwasser-Tagen je Jahreszeit im Zeitverlauf",
       y = "Jährliche durchschnittliche Anzahl von Niedrigwasser-Tagen",
       x = "Datum") +
  facet_wrap(vars(hydro_year))
ggsave("Plots/Chris/analysis/yearly_avg_number_of_low_flow_days_per_season.png", width = 12, height = 6)

```

## Max: Analysis

```{r Max analysis}
theme_map <- theme_bw()+
  theme(panel.grid.major = element_line(colour = "transparent"))

plot(st_geometry(hydro_bavaria))

ggplot()+
  geom_sf(data = hydro_bavaria)



# Plot with catchment points
ggplot()+
  geom_sf(data = hydro_bavaria, fill = "transparent") +
  geom_sf(data = pegel_prop_sf, aes(color = as.factor(unique(ID))), size = 3)+
  labs(color = "Catchment ID")+
  scale_color_viridis_d()+
  theme_map
ggsave("./graphics/Max/Catchments_hydro_bavaria_dots.png", width = 12, height = 9)

# Plot hydrobavaria and admin bavaria
ggplot()+
  geom_sf(data = hydro_bavaria, fill = "white")+
  geom_sf(data = admin_bavaria, fill = "transparent", color = "red")+
  geom_sf(data = pegel_prop_sf, aes(color = as.factor(unique(ID))), size = 3)+
  labs(color = "Catchment ID")+
  scale_color_viridis_d()+
  theme_map
ggsave("./graphics/Max/hydro_admin_bavaria.png", width = 12, height = 9)

# Catchments with rivers and Donau/Main for orientation
waterways_three %>% 
  ggplot()+
  geom_sf(data = hydro_bavaria, fill = "transparent")+
  geom_sf(data = waterways_three, color = "blue", size = 1.5)+
  geom_sf(data = pegel_prop_sf, aes(color = as.factor(unique(ID))), size = 3)+
  labs(color = "Catchment ID")+
  scale_color_viridis_d()+
  theme_map

ggsave("./graphics/Max/map_rivers_catchments.png", width = 12, height = 9)

```

### tmap geographical overview
```{r}
tmap_mode("view")
tm_shape(hydro_bavaria)+
  tm_polygons(id = "NameString")+
  tm_shape(waterways_three)+
  tm_lines(col = "blue")+
  tm_shape(pegel_prop_sf)+
  tm_markers(size = 0.3)
```

## Average plots
```{r}
# boxplots for member distributions in 5 years intervals
plot_avg_member_boxplot <- function(data, var, startYY = 1990, endYY = 2020, by = 5, ...) {
  data %>% 
  group_by(YY, member) %>% 
  filter(YY %in% seq(startYY, endYY, by)) %>% 
  summarise(avg_var= mean(get(var))) %>% 
  mutate(YY = as.factor(YY)) %>% 
  ggplot(aes(x = YY, y = avg_var))+
  geom_boxplot()+
    labs(...)
}

plot_avg_member_boxplot(hydro_winter_10304, var = "drainage", x = "Year", y = "Avg drainage", title = "Winter 10304 (Isar/Mittenwald) Average drainage")
plot_avg_member_boxplot(hydro_winter_10304, var = "airtmp", x = "Year", y = "Avg airtmp", title = "Winter 10304 (Isar/Mittenwald) Average airtmp")
plot_avg_member_boxplot(hydro_winter_10304, var = "soilwater", x = "Year", y = "Avg soilwater", title = "Winter 10304 (Isar/Mittenwald) Average soilwater")
plot_avg_member_boxplot(hydro_winter_10304, var = "precip", x = "Year", y = "Avg precip", title = "Winter 10304 (Isar/Mittenwald) Average precip")

plot_avg_member_boxplot(hydro_summer_10304, var = "drainage", y = "Avg drainage", title = "Summer 10304 (Isar/Mittenwald) Average drainage")
plot_avg_member_boxplot(hydro_summer_10304, var = "airtmp", y = "Avg airtmp", title = "Summer 10304 (Isar/Mittenwald) Average airtmp")
plot_avg_member_boxplot(hydro_summer_10304, var = "soilwater", y = "Avg soilwater", title = "Summer 10304 (Isar/Mittenwald) Average soilwater")
plot_avg_member_boxplot(hydro_summer_10304, var = "precip", y = "Avg precip", title = "Summerr 10304 (Isar/Mittenwald) Average precip")

plot_avg_member_boxplot(hydro_winter_11502, var = "drainage", y = "Avg drainage", title = "Winter 11502 (Iller/Kempten) Average drainage")
plot_avg_member_boxplot(hydro_winter_11502, var = "airtmp", y = "Avg airtmp", title = "Winter 11502 (Iller/Kempten) Average airtmp")
plot_avg_member_boxplot(hydro_winter_11502, var = "soilwater", y = "Avg soilwater", title = "Winter 11502 (Iller/Kempten) Average soilwater")
plot_avg_member_boxplot(hydro_winter_11502, var = "precip", y = "Avg precip", title = "Winter 11502 (Iller/Kempten) Average precip")

plot_avg_member_boxplot(hydro_summer_11502, var = "drainage", y = "Avg drainage", title = "Summer 11502 (Iller/Kempten) Average drainage")
plot_avg_member_boxplot(hydro_summer_11502, var = "airtmp", y = "Avg airtmp", title = "Summer 11502 (Iller/Kempten) Average airtmp")
plot_avg_member_boxplot(hydro_summer_11502, var = "soilwater", y = "Avg soilwater", title = "Summer 11502 (Iller/Kempten) Average soilwater")
plot_avg_member_boxplot(hydro_summer_11502, var = "precip", y = "Avg precip", title = "Summer 11502 (Iller/Kempten) Average precip")

plot_avg_member_boxplot(hydro_winter_20203, var = "drainage", y = "Avg drainage", title = "Winter 20203 (Fränkische Saale/Salz) Average drainage")
plot_avg_member_boxplot(hydro_winter_20203, var = "airtmp", y = "Avg airtmp", title = "Winter 20203 (Fränkische Saale/Salz) Average airtmp")
plot_avg_member_boxplot(hydro_winter_20203, var = "soilwater", y = "Avg soilwater", title = "Winter 20203 (Fränkische Saale/Salz) Average soilwater")
plot_avg_member_boxplot(hydro_winter_20203, var = "precip", y = "Avg precip", title = "Winter 20203 (Fränkische Saale/Salz) Average precip")

plot_avg_member_boxplot(hydro_summer_20203, var = "drainage", y = "Avg drainage", title = "Summer 20203 (Fränkische Saale/Salz) Average drainage")
plot_avg_member_boxplot(hydro_summer_20203, var = "airtmp", y = "Avg airtmp", title = "Summer 20203 (Fränkische Saale/Salz) Average airtmp")
plot_avg_member_boxplot(hydro_summer_20203, var = "soilwater", y = "Avg soilwater", title = "Summer 20203 (Fränkische Saale/Salz) Average soilwater")
plot_avg_member_boxplot(hydro_summer_20203, var = "precip", y = "Avg precip", title = "Summer 20203 (Fränkische Saale/Salz) Average precip")


# average of averages across all members for whole time
plot_averages_across_members <- function(data, var, ...) {
  data %>%
  group_by(YY, member) %>%
  summarise(avg_var = mean(get(var))) %>%
  summarise(avg_var_per_year = mean(avg_var)) %>%
  ggplot(aes(x = YY, y = avg_var_per_year)) +
  geom_point() +
  geom_line() +
    labs(...)
}

plot_averages_across_members(hydro_winter_10304, var = "drainage", y = "Avg drainage across all members", title = "Winter 10304 (Isar/Mittenwald) Avg drainage")
plot_averages_across_members(hydro_winter_10304, var = "airtmp", y = "Avg airtmp across all members", title = "Winter 10304 (Isar/Mittenwald) Avg airtmp")
plot_averages_across_members(hydro_winter_10304, var = "soilwater", y = "Avg soilwater across all members", title = "Winter 10304 (Isar/Mittenwald) Avg soilwater")
plot_averages_across_members(hydro_winter_10304, var = "precip", y = "Avg precip across all members", title = "Winter 10304 (Isar/Mittenwald) Avg precip")

plot_averages_across_members(hydro_summer_10304, var = "drainage", y = "Avg drainage across all members", title = "Summer 10304 (Isar/Mittenwald) Avg drainage")
plot_averages_across_members(hydro_summer_10304, var = "airtmp", y = "Avg airtmp across all members", title = "Summer 10304 (Isar/Mittenwald) Avg airtmp")
plot_averages_across_members(hydro_summer_10304, var = "soilwater", y = "Avg soilwater across all members", title = "Summer 10304 (Isar/Mittenwald) Avg soilwater")
plot_averages_across_members(hydro_summer_10304, var = "precip", y = "Avg precip across all members", title = "Summer 10304 (Isar/Mittenwald) Avg precip")

plot_averages_across_members(hydro_winter_11502, var = "drainage", y = "Avg drainage across all members", title = "Winter 11502 (Iller/Kempten) Avg drainage")
plot_averages_across_members(hydro_winter_11502, var = "airtmp", y = "Avg airtmp across all members", title = "Winter 11502 (Iller/Kempten) Avg airtmp")
plot_averages_across_members(hydro_winter_11502, var = "soilwater", y = "Avg soilwater across all members", title = "Winter 11502 (Iller/Kempten) Avg soilwater")
plot_averages_across_members(hydro_winter_11502, var = "precip", y = "Avg precip across all members", title = "Winter 11502 (Iller/Kempten) Avg precip")

plot_averages_across_members(hydro_summer_11502, var = "drainage", y = "Avg drainage across all members", title = "Summer 11502 (Iller/Kempten) Avg drainage")
plot_averages_across_members(hydro_summer_11502, var = "airtmp", y = "Avg airtmp across all members", title = "Summer 11502 (Iller/Kempten) Avg airtmp")
plot_averages_across_members(hydro_summer_11502, var = "soilwater", y = "Avg soilwater across all members", title = "Summer 11502 (Iller/Kempten) Avg soilwater")
plot_averages_across_members(hydro_summer_11502, var = "precip", y = "Avg precip across all members", title = "Summer 11502 (Iller/Kempten) Avg precip")

plot_averages_across_members(hydro_winter_20203, var = "drainage", y = "Avg drainage across all members", title = "Winter 20203 (Fränkische Saale/Salz) Avg drainage")
plot_averages_across_members(hydro_winter_20203, var = "airtmp", y = "Avg airtmp across all members", title = "Winter 20203 (Fränkische Saale/Salz) Avg airtmp")
plot_averages_across_members(hydro_winter_20203, var = "soilwater", y = "Avg soilwater across all members", title = "Winter 20203 (Fränkische Saale/Salz) Avg soilwater")
plot_averages_across_members(hydro_winter_20203, var = "precip", y = "Avg precip across all members", title = "Winter 20203 (Fränkische Saale/Salz) Avg precip")

plot_averages_across_members(hydro_summer_20203, var = "drainage", y = "Avg drainage across all members", title = "Summer 20203 (Fränkische Saale/Salz) Avg drainage")
plot_averages_across_members(hydro_summer_20203, var = "airtmp", y = "Avg airtmp across all members", title = "Summer 20203 (Fränkische Saale/Salz) Avg airtmp")
plot_averages_across_members(hydro_summer_20203, var = "soilwater", y = "Avg soilwater across all members", title = "Summer 20203 (Fränkische Saale/Salz) Avg soilwater")
plot_averages_across_members(hydro_summer_20203, var = "precip", y = "Avg precip across all members", title = "Summer 20203 (Fränkische Saale/Salz) Avg precip")

```

# Time Series analysis for member kbe and one catchment (should later be genralised)
```{r}
hydro_summer_10304_kbe <- hydro_summer_10304 %>% 
  filter(member %in% "kbe") %>% 
  filter(name_waterlevel == 10304)

ts_hydro_summer_10304_kbe <- zoo(hydro_summer_10304_kbe[5:ncol(hydro_summer_10304_kbe)], hydro_summer_10304_kbe[["date"]])

plot.ts(ts_hydro_summer_10304_kbe$drainage)
plot.ts(window(ts_hydro_summer_10304_kbe$precip, start = '2015-4-01', end = '2015-09-30'))
plot.ts(window(ts_hydro_summer_10304_kbe$soilwater, start = '2015-4-01', end = '2015-09-30'))
plot.ts(window(ts_hydro_summer_10304_kbe$drainage, start = '2015-4-01', end = '2015-09-30'))
```
# Several member visualization
```{r}
hydro_summer_10304 %>% 
  filter(YY %in% seq(1990, 2020, 5)) %>% 
  ggplot(aes(x = date, y = avg_airtmp,col = member)) +
  geom_line(alpha = 0.2)+
  facet_wrap(~ YY, scales = "free_x")
```

```{r}
plot_ts_facet <- function(variable, data, period = 5, ...) {
  data %>% 
  filter(YY %in% seq(1990, 2020, period)) %>% 
  ggplot(aes_string(x = "date", y = variable, col = "member")) +
  geom_path(alpha = 0.2)+
  facet_wrap(~ YY, scales = "free_x")+
    labs(...)
}
```
 
# Summer
```{r}
plot_ts_facet("avg_airtmp", hydro_summer_10304, period = 5, title = 10304)
plot_ts_facet("avg_airtmp", hydro_summer_11502, period = 5, title = 11502)
plot_ts_facet("avg_airtmp", hydro_summer_20203, period = 5, title = 20203)

plot_ts_facet("avg_relhum", hydro_summer_10304, period = 5, title = 10304)
plot_ts_facet("avg_relhum", hydro_summer_11502, period = 5, title = 11502)
plot_ts_facet("avg_relhum", hydro_summer_20203, period = 5, title = 20203)

plot_ts_facet("avg_glorad", hydro_summer_10304, period = 5, title = 10304)
plot_ts_facet("avg_glorad", hydro_summer_11502, period = 5, title = 11502)
plot_ts_facet("avg_glorad", hydro_summer_20203, period = 5, title = 20203)
```

# Winter (needs work on the axis)
```{r}
plot_ts_facet("avg_airtmp", hydro_winter_10304, period = 5, title = 10304)
plot_ts_facet("avg_airtmp", hydro_winter_11502, period = 5, title = 11502)
plot_ts_facet("avg_airtmp", hydro_winter_20203, period = 5, title = 20203)

plot_ts_facet("avg_relhum", hydro_winter_10304, period = 5, title = 10304)
plot_ts_facet("avg_relhum", hydro_winter_11502, period = 5, title = 11502)
plot_ts_facet("avg_relhum", hydro_winter_20203, period = 5, title = 20203)

plot_ts_facet("avg_glorad", hydro_winter_10304, period = 5, title = 10304)
plot_ts_facet("avg_glorad", hydro_winter_11502, period = 5, title = 11502)
plot_ts_facet("avg_glorad", hydro_winter_20203, period = 5, title = 20203)
```

### Glm - Linear trend over time 
```{r}
model_1 <- glm(lowlevel ~ date  + avg_airtmp + avg_soilwater + avg_precip + avg_precip * avg_soilwater, data = hydro_summer_10304_kbe, family = binomial)

summary(model_1)

model_2 <- glm(lowlevel ~ date  + avg_airtmp + avg_soilwater + avg_precip + avg_precip * avg_soilwater + avg_snowstorage + avg_glorad  + avg_infiltration, data = hydro_summer_10304_kbe, family = binomial)

summary(model_2)
```
# GAM
```{r}
library(mgcv)
gam_1 <- gam(lowlevel ~ date  + s(avg_airtmp) + s(avg_soilwater) + s(avg_precip) + avg_precip * avg_soilwater + avg_snowstorage + s(avg_glorad) + s(avg_infiltration), data = hydro_summer_10304_kbe, family = binomial(), method = "REML")
summary(gam_1)

gam_2 <- gam(lowlevel ~ date + s(airtmp) + s(soilwater) + s(precip) + s(soilwater, precip), data = hydro_summer_10304_kbe, family = binomial())
summary(gam_2)

```
# P Splines
```{r}
gam_1_ps <- gam(lowlevel ~ date  + s(avg_airtmp, bs = "ps") + s(avg_soilwater, bs = "ps") + s(avg_precip, bs = "ps") + avg_precip * avg_soilwater + avg_snowstorage + s(avg_glorad, bs = "ps")  + s(avg_infiltration, bs = "ps"), data = hydro_summer_10304_kbe, family = binomial(), method = "REML")
summary(gam_1_ps)

gam_2_ps <- gam(lowlevel ~ date + s(airtmp, bs = "ps") + s(soilwater, bs = "ps") + s(precip, bs = "ps") + s(soilwater, by = precip, bs = "ps"), data = hydro_summer_10304_kbe, family = binomial())

summary(gam_2_ps)
```

### Auto corr
```{r}
# separate datasets for each waterlevel, season and member
# winter
for (i in pegel_ids) {
  for (j in levels(hydro_total$member)) {
    assign(paste0("hydro_winter_", i, "_", j), hydro_winter %>% filter(name_waterlevel %in% i) %>% filter(member %in% j))
  }
}

# summer
for (i in pegel_ids) {
  for (j in levels(hydro_total$member)) {
    assign(paste0("hydro_summer_", i, "_", j), hydro_summer %>% filter(name_waterlevel %in% i) %>% filter(member %in% j))
  }
}


library(car)

## drainage
# autocorrelation function, mean acf for drainage (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_drainage_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_drainage_", k, "_", i, "_", j), as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$drainage, plot = FALSE)$acf))
      assign(paste0("df_acf_drainage_", k, "_", i), bind_cols(get(paste0("df_acf_drainage_", k, "_", i)), get(paste0("acf_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_drainage_", k, "_", i), rowMeans(get(paste0("df_acf_drainage_", k, "_", i))[, 2:11]))
  }
}
# -> Drainage ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for drainage (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_drainage_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_drainage_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_drainage_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_drainage_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_drainage_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_drainage_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between drainage observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# Partial autocorrelation function, mean pacf for drainage (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_drainage_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_drainage_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$drainage, plot = FALSE)$acf))
      assign(paste0("df_pacf_drainage_", k, "_", i),
             bind_cols(get(paste0("df_pacf_drainage_", k, "_", i)), get(paste0("pacf_drainage_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_drainage_", k, "_", i), rowMeans(get(paste0("df_pacf_drainage_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 3 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant

# PACF-Plots for drainage (across all members) separated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_drainage_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_drainage_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_drainage_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_drainage_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_drainage_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_drainage_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between drainage observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## lowlevel
# autocorrelation function, mean acf for lowlevel (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_lowlevel_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_lowlevel_", k, "_", i, "_", j), as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$lowlevel, plot = FALSE)$acf))
      assign(paste0("df_acf_lowlevel_", k, "_", i), bind_cols(get(paste0("df_acf_lowlevel_", k, "_", i)), get(paste0("acf_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_lowlevel_", k, "_", i), rowMeans(get(paste0("df_acf_lowlevel_", k, "_", i))[, 2:11]))
  }
}
# -> Lowlevel ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for lowlevel (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_lowlevel_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_lowlevel_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_lowlevel_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_lowlevel_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_lowlevel_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_lowlevel_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between lowlevel observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# Partial autocorrelation function, mean pacf for lowlevel (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_lowlevel_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_lowlevel_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$lowlevel, plot = FALSE)$acf))
      assign(paste0("df_pacf_lowlevel_", k, "_", i),
             bind_cols(get(paste0("df_pacf_lowlevel_", k, "_", i)), get(paste0("pacf_lowlevel_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_lowlevel_", k, "_", i), rowMeans(get(paste0("df_pacf_lowlevel_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 4 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 4 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant

# PACF-Plots for lowlevel (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_lowlevel_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_lowlevel_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_lowlevel_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_lowlevel_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_lowlevel_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_lowlevel_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between lowlevel observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# DurbinWatsonTest für GAM auf Datensatz hydro_winter_10304_kbe
durbinWatsonTest(gam_1)
# p < 0.05, Wert der Teststatistik: 0.3839 -> Es scheint positive Autokorrelation vorzuliegen

### Driver
## Precip
# autocorrelation function, mean acf for precip (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_precip_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_precip_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$precip, plot = FALSE)$acf))
      assign(paste0("df_acf_precip_", k, "_", i),
             bind_cols(get(paste0("df_acf_precip_", k, "_", i)), get(paste0("acf_precip_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_precip_", k, "_", i), rowMeans(get(paste0("df_acf_precip_", k, "_", i))[, 2:11]))
  }
}
# -> Precip ist in allen Teildatensätzen leicht positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, wäre von Vorteil

# ACF-Plots for precip (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_precip_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_precip_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_precip_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_precip_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_precip_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_precip_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between precip observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for precip (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_precip_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_precip_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$precip, plot = FALSE)$acf))
      assign(paste0("df_pacf_precip_", k, "_", i),
             bind_cols(get(paste0("df_pacf_precip_", k, "_", i)), get(paste0("pacf_precip_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_precip_", k, "_", i), rowMeans(get(paste0("df_pacf_precip_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant

# PACF-Plots for precip (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_precip_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_precip_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_precip_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_precip_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_precip_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_precip_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between precip observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## Airtmp
# autocorrelation function, mean acf for airtmp (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_airtmp_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_airtmp_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$airtmp, plot = FALSE)$acf))
      assign(paste0("df_acf_airtmp_", k, "_", i),
             bind_cols(get(paste0("df_acf_airtmp_", k, "_", i)), get(paste0("acf_airtmp_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_airtmp_", k, "_", i), rowMeans(get(paste0("df_acf_airtmp_", k, "_", i))[, 2:11]))
  }
}
# -> Airtmp ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for airtmp (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_airtmp_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_airtmp_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_airtmp_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_airtmp_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_airtmp_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_airtmp_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between airtmp observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for airtmp (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_airtmp_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_airtmp_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$airtmp, plot = FALSE)$acf))
      assign(paste0("df_pacf_airtmp_", k, "_", i),
             bind_cols(get(paste0("df_pacf_airtmp_", k, "_", i)), get(paste0("pacf_airtmp_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_airtmp_", k, "_", i), rowMeans(get(paste0("df_pacf_airtmp_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 7 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 5 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 7 (nicht durchgängig), bis lag = 3 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 5 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 6 (durchgängig) signifikant

# PACF-Plots for airtmp (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_airtmp_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_airtmp_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_airtmp_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_airtmp_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_airtmp_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_airtmp_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between airtmp observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

## Glorad
# autocorrelation function, mean acf for glorad (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_glorad_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_glorad_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$glorad, plot = FALSE)$acf))
      assign(paste0("df_acf_glorad_", k, "_", i),
             bind_cols(get(paste0("df_acf_glorad_", k, "_", i)), get(paste0("acf_glorad_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_glorad_", k, "_", i), rowMeans(get(paste0("df_acf_glorad_", k, "_", i))[, 2:11]))
  }
}
# -> Glorad ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for glorad (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_glorad_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_glorad_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_glorad_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_glorad_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_glorad_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_glorad_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between glorad observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for glorad (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_glorad_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_glorad_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$glorad, plot = FALSE)$acf))
      assign(paste0("df_pacf_glorad_", k, "_", i),
             bind_cols(get(paste0("df_pacf_glorad_", k, "_", i)), get(paste0("pacf_glorad_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_glorad_", k, "_", i), rowMeans(get(paste0("df_pacf_glorad_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 7 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 9 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 7 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 8 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 6 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 7 (durchgängig) signifikant

# PACF-Plots for glorad (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_glorad_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_glorad_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_glorad_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_glorad_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_glorad_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_glorad_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between glorad observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## Relhum
# autocorrelation function, mean acf for relhum (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_relhum_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_relhum_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$relhum, plot = FALSE)$acf))
      assign(paste0("df_acf_relhum_", k, "_", i),
             bind_cols(get(paste0("df_acf_relhum_", k, "_", i)), get(paste0("acf_relhum_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_relhum_", k, "_", i), rowMeans(get(paste0("df_acf_relhum_", k, "_", i))[, 2:11]))
  }
}
# -> Relhum ist in allen Teildatensätzen positiv autokorreliert (vor allem für Pegel 20203) -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for relhum (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_relhum_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_relhum_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_relhum_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_relhum_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_relhum_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_relhum_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between relhum observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for relhum (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_relhum_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_relhum_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$relhum, plot = FALSE)$acf))
      assign(paste0("df_pacf_relhum_", k, "_", i),
             bind_cols(get(paste0("df_pacf_relhum_", k, "_", i)), get(paste0("pacf_relhum_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_relhum_", k, "_", i), rowMeans(get(paste0("df_pacf_relhum_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 5 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 4 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant

# PACF-Plots for relhum (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_relhum_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_relhum_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_relhum_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_relhum_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_relhum_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_relhum_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between relhum observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

## Soilwater
# autocorrelation function, mean acf for soilwater (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_soilwater_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_soilwater_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$soilwater, plot = FALSE)$acf))
      assign(paste0("df_acf_soilwater_", k, "_", i),
             bind_cols(get(paste0("df_acf_soilwater_", k, "_", i)), get(paste0("acf_soilwater_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_soilwater_", k, "_", i), rowMeans(get(paste0("df_acf_soilwater_", k, "_", i))[, 2:11]))
  }
}
# -> Soilwater ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for soilwater (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_soilwater_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_soilwater_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_soilwater_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_soilwater_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_soilwater_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_soilwater_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between soilwater observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for soilwater (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_soilwater_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_soilwater_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$soilwater, plot = FALSE)$acf))
      assign(paste0("df_pacf_soilwater_", k, "_", i),
             bind_cols(get(paste0("df_pacf_soilwater_", k, "_", i)), get(paste0("pacf_soilwater_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_soilwater_", k, "_", i), rowMeans(get(paste0("df_pacf_soilwater_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant

# PACF-Plots for soilwater (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_soilwater_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_soilwater_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_soilwater_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_soilwater_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_soilwater_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_soilwater_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between soilwater observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## Snowstorage
# autocorrelation function, mean acf for snowstorage (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_snowstorage_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_snowstorage_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$snowstorage, plot = FALSE)$acf))
      assign(paste0("df_acf_snowstorage_", k, "_", i),
             bind_cols(get(paste0("df_acf_snowstorage_", k, "_", i)), get(paste0("acf_snowstorage_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_snowstorage_", k, "_", i), rowMeans(get(paste0("df_acf_snowstorage_", k, "_", i))[, 2:11]))
  }
}
# -> Snowstorage ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for snowstorage (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_snowstorage_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_snowstorage_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_snowstorage_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_snowstorage_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_snowstorage_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_snowstorage_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between snowstorage observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for snowstorage (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_snowstorage_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_snowstorage_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$snowstorage, plot = FALSE)$acf))
      assign(paste0("df_pacf_snowstorage_", k, "_", i),
             bind_cols(get(paste0("df_pacf_snowstorage_", k, "_", i)), get(paste0("pacf_snowstorage_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_snowstorage_", k, "_", i), rowMeans(get(paste0("df_pacf_snowstorage_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 4 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant

# PACF-Plots for snowstorage (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_snowstorage_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_snowstorage_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_snowstorage_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_snowstorage_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_snowstorage_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_snowstorage_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between snowstorage observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## Groundwaterdepth
# autocorrelation function, mean acf for groundwaterdepth (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_groundwaterdepth_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_groundwaterdepth_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$groundwaterdepth, plot = FALSE)$acf))
      assign(paste0("df_acf_groundwaterdepth_", k, "_", i),
             bind_cols(get(paste0("df_acf_groundwaterdepth_", k, "_", i)), get(paste0("acf_groundwaterdepth_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_groundwaterdepth_", k, "_", i), rowMeans(get(paste0("df_acf_groundwaterdepth_", k, "_", i))[, 2:11]))
  }
}
# -> Groundwaterdepth ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for groundwaterdepth (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_groundwaterdepth_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_groundwaterdepth_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_groundwaterdepth_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_groundwaterdepth_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_groundwaterdepth_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_groundwaterdepth_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between groundwaterdepth observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for groundwaterdepth (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_groundwaterdepth_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_groundwaterdepth_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$groundwaterdepth, plot = FALSE)$acf))
      assign(paste0("df_pacf_groundwaterdepth_", k, "_", i),
             bind_cols(get(paste0("df_pacf_groundwaterdepth_", k, "_", i)), get(paste0("pacf_groundwaterdepth_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_groundwaterdepth_", k, "_", i), rowMeans(get(paste0("df_pacf_groundwaterdepth_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 3 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 5 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant

# PACF-Plots for groundwaterdepth (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_groundwaterdepth_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_groundwaterdepth_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_groundwaterdepth_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_groundwaterdepth_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_groundwaterdepth_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_groundwaterdepth_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between groundwaterdepth observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")


## Infiltration
# autocorrelation function, mean acf for infiltration (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_acf_infiltration_", k, "_", i), data.frame(Names = 1:38))
    for (j in levels(hydro_total$member)) {
      assign(paste0("acf_infiltration_", k, "_", i, "_", j),
             as.data.frame(acf(get(paste0("hydro_", k, "_", i, "_", j))$infiltration, plot = FALSE)$acf))
      assign(paste0("df_acf_infiltration_", k, "_", i),
             bind_cols(get(paste0("df_acf_infiltration_", k, "_", i)), get(paste0("acf_infiltration_", k, "_", i, "_", j))))
    }
    assign(paste0("acf_mean_infiltration_", k, "_", i), rowMeans(get(paste0("df_acf_infiltration_", k, "_", i))[, 2:11]))
  }
}
# -> Infiltration ist in allen Teildatensätzen positiv autokorreliert -> Modell, das diese Autokorrelation berücksichtigt, nötig

# ACF-Plots for infiltration (across all members) separated by each waterlevel and season
plot(x = 0:37, y = acf_mean_infiltration_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_infiltration_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_infiltration_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_infiltration_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_infiltration_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 0:37, y = acf_mean_infiltration_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Autocorrelation between infiltration observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

# partial autocorrelation function, mean pacf for infiltration (across all members) separated by each waterlevel and season
for (k in c("winter", "summer")) {
  for (i in pegel_ids) {
    assign(paste0("df_pacf_infiltration_", k, "_", i), data.frame(Names = 1:37))
    for (j in levels(hydro_total$member)) {
      assign(paste0("pacf_infiltration_", k, "_", i, "_", j),
             as.data.frame(pacf(get(paste0("hydro_", k, "_", i, "_", j))$infiltration, plot = FALSE)$acf))
      assign(paste0("df_pacf_infiltration_", k, "_", i),
             bind_cols(get(paste0("df_pacf_infiltration_", k, "_", i)), get(paste0("pacf_infiltration_", k, "_", i, "_", j))))
    }
    assign(paste0("pacf_mean_infiltration_", k, "_", i), rowMeans(get(paste0("df_pacf_infiltration_", k, "_", i))[, 2:11]))
  }
}
# 10304, Winter: Autokorrelationskoeffizient bis lag = 6 (durchgängig) signifikant
# 10304, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 11502, Winter: Autokorrelationskoeffizient bis lag = 3 (nicht durchgängig), bis lag = 1 (durchgängig) signifikant
# 11502, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant
# 20203, Winter: Autokorrelationskoeffizient bis lag = 2 (durchgängig) signifikant
# 20203, Summer: Autokorrelationskoeffizient bis lag = 1 (durchgängig) signifikant

# PACF-Plots for infiltration (across all members) seperated by each waterlevel and season
plot(x = 1:37, y = pacf_mean_infiltration_winter_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 10304, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_infiltration_summer_10304, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 10304, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_infiltration_winter_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 11502, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_infiltration_summer_11502, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 11502, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_infiltration_winter_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 20203, winter") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")
plot(x = 1:37, y = pacf_mean_infiltration_summer_20203, ylim = c(-0.1, 1), type = "h", xlab = "lag in days", ylab = "ACF", main = "Partial autocorrelation between infiltration observations for 20203, summer") + abline(h = 0) + abline(h = c(-0.05, 0.05), col = "blue", lty = "dashed")

```


https://online.stat.psu.edu/stat501/book/export/html/996#:~:text=The%20order%20of%20an%20autoregression,written%20as%20AR(1)
# Lag DF
```{r}
lag_df <- function(dat, lag) {
  data.frame(unclass(dat[c(rep(NA, lag), 1:(nrow(dat)-lag)),]))
}

ggplot(aes(x = (lag(hydro_summer_10304_kbe$airtmp, 3)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$soilwater, 2)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$precip, 2)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)

ggplot(aes(x = (lag(hydro_summer_10304_kbe$avg_precip, 0)), y = hydro_summer_10304_kbe$drainage), data = hydro_summer_10304_kbe)+
  geom_point(alpha = 0.2)
```

# ARDLM
```{r}
ardlDlm_1 <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp + glorad, data = hydro_summer_10304_kbe, p = 2, q = 2)

summary(ardlDlm_1)
```


```{r}

results_ardldlm_10304 <- list()
i <- 1
for (member in unique(hydro_summer_10304$member)){
  data <- hydro_summer_10304[hydro_summer_10304["member"] == member,]
  results_ardldlm_10304[i] <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp, data = data, p = 3, q = 2)
  i <- i+ 1
}

lapply(results_ardldlm_10304, summary)

```
```{r}
results_ardldlm_11502 <- list()
i <- 1
for (member in unique(hydro_summer_10304$member)){
  data <- hydro_summer_11502[hydro_summer_11502["member"] == member,]
  results_ardldlm_11502[i] <- ardlDlm(formula = drainage ~ soilwater + precip + snowstorage + airtmp, data = data, p = 3, q = 2)
  i <- i+ 1
}

lapply(results_ardldlm_11502, summary)
```

```{r}
fit_ardlm_across <- function(formula, data, p, q, summary_output = TRUE) {
  results <- list()
i <- 1
for (member in unique(data$member)){
  data_loop <- data[data["member"] == member,]
  results[i] <- ardlDlm(formula = formula, data = data_loop, p = p, q = q)
  i <- i+ 1
}

lapply(results, summary)
}
```
# Summer
```{r}
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_10304, p = 3, q = 4)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_11502, p = 3, q = 4)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp + glorad, data = hydro_summer_20203, p = 3, q = 4)


lapply(fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_summer_20203, p = 2, q = 2), "[[", "adj.r.squared")
```
# Winter
```{r}
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_10304, p = 3, q = 2)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_11502, p = 3, q = 2)
fit_ardlm_across(drainage ~ soilwater + precip + snowstorage + airtmp, data = hydro_winter_20203, p = 3, q = 2)
```

```{r}
rolCorPlot(ts_hydro_summer_10304_kbe)
```


## Lisa: Analysis

```{r Lisa analysis}
hydro_winter <- readRDS(file = "./data/hydro_winter.RDS")
hydro_summer <- readRDS(file = "./data/hydro_summer.RDS")
 
  
plot_cor_drainage <- function(data, var, ...) {
  ggplot(data, aes(x = get(var), y = drainage)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", col = "red") +
  labs(...)
}


# Airtmp
cor_airtmp <- numeric(length = 6)
plot_cor_drainage(data = hydro_winter_10304, var = "airtmp", x = "airtmp", title = "Winter 10304 (Isar/Mittenwald) correlation airtmp and drainage")
cor_airtmp[1] <- cor(hydro_winter_10304$drainage, hydro_winter_10304$airtmp)
plot_cor_drainage(data = hydro_summer_10304, var = "airtmp", x = "airtmp", title = "Summer 10304 (Isar/Mittenwald) correlation airtmp and drainage")
cor_airtmp[2] <- cor(hydro_summer_10304$drainage, hydro_summer_10304$airtmp)

plot_cor_drainage(data = hydro_winter_11502, var = "airtmp", x = "airtmp", title = "Winter 11502 (Iller/Kempten) correlation airtmp and drainage")
cor_airtmp[3] <- cor(hydro_winter_11502$drainage, hydro_winter_11502$airtmp)
plot_cor_drainage(data = hydro_summer_11502, var = "airtmp", x = "airtmp", title = "Summer 11502 (Iller/Kempten) correlation airtmp and drainage")
cor_airtmp[4] <- cor(hydro_summer_11502$drainage, hydro_summer_11502$airtmp)

plot_cor_drainage(data = hydro_winter_20203, var = "airtmp", x = "airtmp", title = "Winter 20203 (Fränkische Saale/Salz) correlation airtmp and drainage")
cor_airtmp[5] <- cor(hydro_winter_20203$drainage, hydro_winter_20203$airtmp)
plot_cor_drainage(data = hydro_summer_20203, var = "airtmp", x = "airtmp", title = "Summer 20203 (Fränkische Saale/Salz) correlation airtmp and drainage")
cor_airtmp[6] <- cor(hydro_summer_20203$drainage, hydro_summer_20203$airtmp)

var(cor_airtmp)

# Soilwater
cor_soilwater <- numeric(length = 6)
plot_cor_drainage(data = hydro_winter_10304, var = "soilwater", x = "soilwater", title = "Winter 10304 (Isar/Mittenwald) correlation soilwater and drainage")
cor_soilwater[1] <- cor(hydro_winter_10304$drainage, hydro_winter_10304$soilwater)
plot_cor_drainage(data = hydro_summer_10304, var = "soilwater", x = "soilwater", title = "Summer 10304 (Isar/Mittenwald) correlation soilwater and drainage")
cor_soilwater[2] <- cor(hydro_summer_10304$drainage, hydro_summer_10304$soilwater)

plot_cor_drainage(data = hydro_winter_11502, var = "soilwater", x = "soilwater", title = "Winter 11502 (Iller/Kempten) correlation soilwater and drainage")
cor_soilwater[3] <- cor(hydro_winter_11502$drainage, hydro_winter_11502$soilwater)
plot_cor_drainage(data = hydro_summer_11502, var = "soilwater", x = "soilwater", title = "Summer 11502 (Iller/Kempten) correlation soilwater and drainage")
cor_soilwater[4] <- cor(hydro_summer_11502$drainage, hydro_summer_11502$soilwater)

plot_cor_drainage(data = hydro_winter_20203, var = "soilwater", x = "soilwater", title = "Winter 20203 (Fränkische Saale/Salz) correlation soilwater and drainage")
cor_soilwater[5] <- cor(hydro_winter_20203$drainage, hydro_winter_20203$soilwater)
plot_cor_drainage(data = hydro_summer_20203, var = "soilwater", x = "soilwater", title = "Summer 20203 (Fränkische Saale/Salz) correlation soilwater and drainage")
cor_soilwater[6] <- cor(hydro_summer_20203$drainage, hydro_summer_20203$soilwater)

var(cor_soilwater)


# Precip
cor_precip <- numeric(length = 6)
plot_cor_drainage(data = hydro_winter_10304, var = "precip", x = "precip", title = "Winter 10304 (Isar/Mittenwald) correlation precip and drainage")
cor_precip[1] <- cor(hydro_winter_10304$drainage, hydro_winter_10304$precip)
plot_cor_drainage(data = hydro_summer_10304, var = "precip", x = "precip", title = "Summer 10304 (Isar/Mittenwald) correlation precip and drainage")
cor_precip[2] <- cor(hydro_summer_10304$drainage, hydro_summer_10304$precip)

plot_cor_drainage(data = hydro_winter_11502, var = "precip", x = "precip", title = "Winter 11502 (Iller/Kempten) correlation precip and drainage")
cor_precip[3] <- cor(hydro_winter_11502$drainage, hydro_winter_11502$precip)
plot_cor_drainage(data = hydro_summer_11502, var = "precip", x = "precip", title = "Summer 11502 (Iller/Kempten) correlation precip and drainage")
cor_precip[4] <- cor(hydro_summer_11502$drainage, hydro_summer_11502$precip)

plot_cor_drainage(data = hydro_winter_20203, var = "precip", x = "precip", title = "Winter 20203 (Fränkische Saale/Salz) correlation precip and drainage")
cor_precip[5] <- cor(hydro_winter_20203$drainage, hydro_winter_20203$precip)
plot_cor_drainage(data = hydro_summer_20203, var = "precip", x = "precip", title = "Summer 20203 (Fränkische Saale/Salz) correlation precip and drainage")
cor_precip[6] <- cor(hydro_summer_20203$drainage, hydro_summer_20203$precip)

var(cor_precip)

# not differentiated by waterlevels
library(corrplot)

# winter
correlationm_spearman_winter <- cor(subset(hydro_winter, select = c(drainage, airtmp, soilwater, precip, glorad, relhum, snowstorage, groundwaterdepth, infiltration)), method = "spearman")
correlationp_spearman_winter <- cor.mtest(correlationm_spearman_winter)
# correlation with soilwater and with groundwaterdepth significant at level = 0.05
corrplot.mixed(correlationm_spearman_winter, upper = "circle", lower = "number", lower.col = "black")
corrplot.mixed(correlationm_spearman_winter, upper = "circle", lower = "number", lower.col = "black", p.mat = correlationp_spearman_winter$p)

# summer
correlationm_spearman_summer <- cor(subset(hydro_summer, select = c(drainage, airtmp, soilwater, precip, glorad, relhum, snowstorage, groundwaterdepth, infiltration)), method = "spearman")
correlationp_spearman_summer <- cor.mtest(correlationm_spearman_summer)
# correlation with airtmp, soilwater and snowstorage significant at level = 0.05
corrplot.mixed(correlationm_spearman_summer, upper = "circle", lower = "number", lower.col = "black")
corrplot.mixed(correlationm_spearman_summer, upper = "circle", lower = "number", lower.col = "black", p.mat = correlationp_spearman_summer$p)


# plots drainage and drivers over time
plot_single_drainage_and_driver <- function(dataset, var, per_year = TRUE, years = 1990:2020, member_input = "kbe") {
  data <- dataset %>% filter(member == member_input, YY %in% years) %>% group_by(YY)
  if (per_year == TRUE) {
    data <- data %>% summarise(avg_drainage = mean(drainage), avg_var = mean(get(var)))
    plot <- data %>% ggplot() +
      geom_line(mapping = aes(x = YY, y = avg_drainage), col = "blue") +
      geom_point(aes(x = YY, y = avg_drainage), col = "blue") +
      geom_point(aes(x = YY, y = avg_var), col = "red") +
      geom_line(aes(x = YY, y = avg_var), col = "red") +
      scale_y_continuous("drainage in blue", sec.axis = sec_axis(trans = ~., name = paste(as.character(var), "in red")))
  } else {
    plot <- data %>% ggplot() +
      geom_line(mapping = aes(x = date, y = drainage), col = "blue") +
      geom_point(aes(x = date, y = drainage), col = "blue") +
      geom_point(aes(x = date, y = get(var)), col = "red") +
      geom_line(aes(x = date, y = get(var)), col = "red") +
      scale_y_continuous("drainage in blue", sec.axis = sec_axis(trans = ~., name = paste(as.character(var), "in red")))
  }
  plot
}

plot_single_drainage_and_driver(hydro_total %>% filter(name_waterlevel == 10304), var = "avg_airtmp", year = 2000:2003, per_year = FALSE)
```
## Jonas: Analysis

```{r Jonas analysis}
summary(cars)
```